import { formatMessage } from '../../generated/localizations.ts';
import { randomUUID } from "node:crypto";
import { AppError } from '../../shared/errors.ts';
import { LANGUAGES, type Language } from '../../shared/programming.ts';
import { object, text } from '../../shared/input.ts';
import { interviewContent, type Question, type Source } from "../interview/domain.ts";

export const TRAINING_KINDS = { compression: formatMessage('zh', "ui.answerCompression"), followup: formatMessage('zh', "ui.progressiveFollowUps"), diagnosis: formatMessage('zh', "ui.engineeringBugDiagnosis"), debrief: formatMessage('zh', "ui.actualInterviewDebrief") } as const;
export const DIAGNOSIS_TOPICS = { state: formatMessage('zh', "ui.stateOverwritesAndRaces"), requests: formatMessage('zh', "ui.duplicateRequestsAndRetries"), async: formatMessage('zh', "ui.asyncCancellationAndLifecycle"), collections: formatMessage('zh', "ui.collectionsBoundariesAndMutability"), resources: formatMessage('zh', "ui.resourceManagementAndRecovery") } as const;
export type TrainingKind = keyof typeof TRAINING_KINDS;
export type Draft = Record<string, string>;
export type Scenario = { description: string; symptoms: string[]; expected: string; requirements: string[]; faultyCode: string; cases: { input: string; expected: string }[]; reference: { cause: string; fixedCode: string; explanation: string; checks: string[] } };
export type Turn = Question & { submittedAnswer?: string; feedback?: FollowupResult["feedback"] };
export type TrainingReview = { id: string; at: string; action: string; model: string; input: Draft; result: CompressionResult | DiagnosisResult | DebriefResult };
export type Training = { id: string; kind: TrainingKind; title: string; createdAt: string; updatedAt: string; draft: Draft; sources: Source[]; reviews: TrainingReview[];
  question?: string; interviewId?: string; questionId?: string; language?: Language; topic?: keyof typeof DIAGNOSIS_TOPICS; scenario?: Scenario; revealedAt?: string; turns?: Turn[]; finished?: boolean; stopReason?: string; debriefId?: string; entryId?: string };
export type CompressionResult = { summary: string; relevance: string; conciseness: string; fidelity: string; cuts: { quote: string; reason: string }[]; missing: string[]; keywords: string[]; comparison: string };
export type FollowupResult = { feedback: { summary: string; technical: string; evidence: string; expression: string; gaps: string[]; keywords: string[] }; next: Question | null; stopReason: string };
export type DiagnosisResult = { summary: string; cause: string; repair: string; validation: string; strengths: string[]; gaps: string[]; nextSteps: string[] };
export type DebriefResult = { summary: string; observations: { entryId: string; content: string; expression: string; evidence: string; practice: string; keywords: string[] }[]; priorities: { entryId: string; kind: "compression" | "followup" | "diagnosis"; title: string; reason: string }[]; nextSteps: string[] };
export const stamp = () => new Date().toISOString();
export function strings(value: unknown, min=0, max=5, limit=300): string[] { if(!Array.isArray(value)||value.length<min||value.length>max)throw new AppError(400,formatMessage('zh', "ui.incorrectNumberOfKeyPoints"));return value.map(v=>text(v,limit).trim()); }
function optional(value: unknown, limit: number) { if(value===undefined)return "";if(typeof value!=="string"||value.length>limit)throw new AppError(400,formatMessage('zh', "ui.theTextFormatIsIncorrectOrTooLong"));return value; }
export function trainingRecord(kind: TrainingKind, title: string, draft: Draft, sources: Source[]=[]): Training { const at=stamp();return {id:randomUUID(),kind,title,createdAt:at,updatedAt:at,draft,sources,reviews:[]}; }
export function diagnosisSelection(value: unknown) { const v=object(value);if(!Object.hasOwn(LANGUAGES,v.language as string)||!Object.hasOwn(DIAGNOSIS_TOPICS,v.topic as string))throw new AppError(400,formatMessage('zh', "ui.pleaseChooseAFaultAreaAndLanguage"));return {language:v.language as Language,topic:v.topic as keyof typeof DIAGNOSIS_TOPICS,focus:optional(v.focus,1000)}; }
export function scenarioContent(value: unknown) {
  const v=object(value),r=object(v.reference);if(!Array.isArray(v.cases)||v.cases.length<2||v.cases.length>4)throw new AppError(400,formatMessage('zh', "ui.theIncidentCaseIsIncomplete"));
  return {title:text(v.title,150),scenario:{description:text(v.description,3000),symptoms:strings(v.symptoms,1,4),expected:text(v.expected,1000),requirements:strings(v.requirements,1,5),faultyCode:text(v.faultyCode,18000),cases:v.cases.map(c=>{const x=object(c);return{input:text(x.input,1000),expected:text(x.expected,1000)};}),reference:{cause:text(r.cause,1500),fixedCode:text(r.fixedCode,18000),explanation:text(r.explanation,2000),checks:strings(r.checks,2,5)}} satisfies Scenario};
}
export function draftInput(value: unknown, record: Training): Draft {
  const v=object(object(value).draft),out:Draft={};
  const valid=new Set(record.kind==="compression"?["original","points"]:record.kind==="diagnosis"?["code","cause","checks"]:record.kind==="followup"?record.turns!.map(t=>`answer:${t.id}`):["company","role","date","stage","notes",...Array.from({length:8},(_,i)=>[`question:${i+1}`,`answer:${i+1}`,`feedback:${i+1}`]).flat()]);
  for(const [key,value] of Object.entries(v)){if(!valid.has(key))throw new AppError(400,formatMessage('zh', "ui.invalidDraftField"));out[key]=optional(value,key==="code"?100000:key==="points"?1000:["company","role","stage"].includes(key)?150:key==="date"?10:10000);}
  return out;
}
export function compressionInput(value: unknown,record:Training,action:string) { const draft=draftInput(value,record),original=text(draft.original,10000);if(action==="rewrite"){const points=strings((draft.points??"").split(/\n/).map(s=>s.trim()).filter(Boolean),3,5,80);draft.points=points.join("\n");}return {...draft,original}; }
export function compressionResult(value: unknown,original:string):CompressionResult { const v=object(value);if(!Array.isArray(v.cuts)||v.cuts.length>3)throw new AppError(400,formatMessage('zh', "ui.theReductionSuggestionIsInvalid"));return {summary:text(v.summary,500),relevance:text(v.relevance,400),conciseness:text(v.conciseness,400),fidelity:text(v.fidelity,400),cuts:v.cuts.map(c=>{const x=object(c),quote=text(x.quote,200);if(!original.includes(quote))throw new AppError(400,formatMessage('zh', "ui.theReductionSuggestionReferencesOriginalTextThatDoes"));return {quote,reason:text(x.reason,300)};}),missing:strings(v.missing,0,3),keywords:strings(v.keywords,3,5,80),comparison:text(v.comparison,500)}; }
export function followupResult(value:unknown,sources:Source[],lastTurn:boolean):FollowupResult { const v=object(value),f=object(v.feedback);const next=v.next===null?null:interviewContent({title:"追问",introduction:"递进练习",questions:[v.next]},1,sources).questions[0];if(lastTurn&&next)throw new AppError(400,formatMessage('zh', "ui.thisRoundHasReachedEightQuestionsPleaseFinish"));return {feedback:{summary:text(f.summary,500),technical:text(f.technical,400),evidence:text(f.evidence,400),expression:text(f.expression,400),gaps:strings(f.gaps,0,3),keywords:strings(f.keywords,3,5,80)},next,stopReason:next?optional(v.stopReason,400):text(v.stopReason,400)}; }
export function diagnosisResult(value:unknown):DiagnosisResult { const v=object(value);return {summary:text(v.summary,600),cause:text(v.cause,600),repair:text(v.repair,600),validation:text(v.validation,600),strengths:strings(v.strengths,0,3),gaps:strings(v.gaps,0,4),nextSteps:strings(v.nextSteps,1,4)}; }
export function debriefEntries(draft:Draft) { const entries=[];for(let n=1;n<=8;n++){const question=draft[`question:${n}`]?.trim(),answer=draft[`answer:${n}`]??"",feedback=draft[`feedback:${n}`]??"";if(!question){if(answer.trim()||feedback.trim())throw new AppError(400,formatMessage('zh', "ui.fillInTheCorrespondingQuestionBeforeAddingAn"));continue;}entries.push({id:String(n),question,answer,feedback});}if(!entries.length)throw new AppError(400,formatMessage('zh', "ui.pleaseRecordAtLeastOneActualInterviewQuestion"));return entries; }
export function debriefResult(value:unknown,ids:string[]):DebriefResult { const v=object(value);if(!Array.isArray(v.observations)||v.observations.length!==ids.length||!Array.isArray(v.priorities)||v.priorities.length<1||v.priorities.length>3)throw new AppError(400,formatMessage('zh', "ui.theReviewScopeIsIncorrect"));const seen=new Set<string>();return {summary:text(v.summary,600),observations:v.observations.map(o=>{const x=object(o),id=text(x.entryId,10);if(!ids.includes(id)||seen.has(id))throw new AppError(400,formatMessage('zh', "ui.theReviewReferencesAnUnknownQuestion"));seen.add(id);return {entryId:id,content:text(x.content,500),expression:text(x.expression,500),evidence:text(x.evidence,500),practice:text(x.practice,500),keywords:strings(x.keywords,3,5,80)};}),priorities:v.priorities.map(p=>{const x=object(p),entryId=text(x.entryId,10);if(!ids.includes(entryId)||!["compression","followup","diagnosis"].includes(x.kind as string))throw new AppError(400,formatMessage('zh', "ui.invalidTrainingDirection"));return {entryId,kind:x.kind as DebriefResult["priorities"][number]["kind"],title:text(x.title,150),reason:text(x.reason,400)};}),nextSteps:strings(v.nextSteps,1,4)}; }
export function publicTraining(record:Training) { const {scenario,...rest}=record;const sources=record.sources.map(({content:_,...s})=>s);return {...rest,sources,...(scenario?{scenario:record.revealedAt?scenario:(({reference:_,...publicScenario})=>publicScenario)(scenario)}:{})}; }
