import { execFileSync } from 'node:child_process';
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve, posix } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
import { format } from 'prettier';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const output = resolve(root, 'src/generated/codex');
const checking = process.argv.includes('--check');
const scratch = await mkdtemp(join(tmpdir(), 'recruitagent-codex-'));
const executable = resolve(root, 'node_modules/@openai/codex/bin/codex.js');
try {
  const version = execFileSync(process.execPath, [executable, '--version'], { encoding: 'utf8' }).trim();
  execFileSync(process.execPath, [executable, 'app-server', 'generate-ts', '--experimental', '--out', join(scratch, 'types')], { stdio: 'pipe' });
  execFileSync(process.execPath, [executable, 'app-server', 'generate-json-schema', '--experimental', '--out', join(scratch, 'schemas')], { stdio: 'pipe' });
  const files = { 'version.json': JSON.stringify({ cli: version }, null, 2) + '\n' };
  async function readTree(directory, prefix = '') {
    for (const entry of (await readdir(directory, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name, 'en'))) {
      const path = join(directory, entry.name), name = prefix + entry.name;
      if (entry.isDirectory()) await readTree(path, name + '/');
      else {
        const raw = await readFile(path, 'utf8');
        // NodeNext consumers require extensions; keep generated protocol meaning unchanged.
        files[name] = name.endsWith('.ts') ? await format(raw.replace(/from "(\.[^"]+)"/g, 'from "$1.js"'), { parser: 'typescript' }) : raw;
      }
    }
  }
  await readTree(join(scratch, 'types'));
  // Keep the authoritative protocol schemas alongside bindings for runtime adapters and upgrades.
  await readTree(join(scratch, 'schemas'), 'schemas/');
  for (const [name, content] of Object.entries(files)) if (name.endsWith('.ts')) {
    files[name] = content.replace(/from "(\.[^"]+)\.js"/g, (text, specifier) => Object.hasOwn(files, posix.join(posix.dirname(name), specifier, 'index.ts')) ? `from "${specifier}/index.js"` : text);
  }
  const ast = ts.createSourceFile('ClientRequest.ts', files['ClientRequest.ts'], ts.ScriptTarget.Latest, true);
  const methods = [];
  function visit(node) {
    if (ts.isTypeLiteralNode(node)) {
      const method = node.members.find(m => m.name?.getText(ast).replaceAll('"', '') === 'method');
      const params = node.members.find(m => m.name?.getText(ast).replaceAll('"', '') === 'params');
      if (method?.type && params?.type && ts.isLiteralTypeNode(method.type)) {
        const param = params.type.getText(ast), response = param.replace(/Params$/, 'Response');
        const path = Object.keys(files).find(path => path === `${response}.ts` || path === `v2/${response}.ts`);
        if (path) methods.push(`  ${method.type.getText(ast)}: import('./${path.replace('.ts', '.js')}').${response};`);
      }
    }
    ts.forEachChild(node, visit);
  }
  visit(ast);
  files['rpc-responses.ts'] = '// Generated by npm run generate:codex. Do not edit.\nexport interface RpcResponses {\n' + methods.join('\n') + '\n}\n';
  const existing = [];
  async function listGenerated(directory, prefix = '') {
    for (const entry of await readdir(directory, { withFileTypes: true }).catch(() => [])) {
      if (entry.isDirectory()) await listGenerated(join(directory, entry.name), prefix + entry.name + '/');
      else existing.push(prefix + entry.name);
    }
  }
  await listGenerated(output);
  const extras = existing.filter(name => !Object.hasOwn(files, name));
  if (!checking) for (const name of extras) await rm(resolve(output, name));
  const stale = checking ? [...extras] : [];
  for (const [name, content] of Object.entries(files)) {
    const path = resolve(output, name);
    if (checking) { if (await readFile(path, 'utf8').catch(() => '') !== content) stale.push(name); }
    else { await mkdir(dirname(path), { recursive: true }); await writeFile(path, content); }
  }
  if (stale.length) throw new Error(`Codex protocol artifacts are stale (${stale.length} files). Run npm run generate:codex.`);
  console.log(`Codex protocol ${checking ? 'verified' : 'generated'}: ${version}, ${methods.length} method/response associations.`);
} finally { await rm(scratch, { recursive: true, force: true }); }
