import { readFile, writeFile, readdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const locales = ['zh', 'ja', 'en'];
const serialize = value => JSON.stringify(value, null, 2);
export const placeholders = value => [...new Set([...value.matchAll(/\{([a-zA-Z][\w]*)\}/g)].map(match => match[1]))].sort();

export function validateResources(resources) {
  const source = resources.zh;
  if (!source || typeof source !== 'object' || Array.isArray(source)) throw new Error('Missing zh resources.');
  const keys = Object.keys(source).sort();
  for (const key of keys) if (!/^[a-z][\w.]*$/.test(key)) throw new Error(`Use a stable identifier for ${key}`);
  for (const locale of locales) {
    const entries = resources[locale];
    if (!entries || JSON.stringify(Object.keys(entries).sort()) !== JSON.stringify(keys)) throw new Error(`${locale}: resource keys do not match zh.`);
    for (const key of keys) {
      const text = entries[key];
      if (typeof text !== 'string' || !text.trim()) throw new Error(`${locale}: missing translation for ${key}`);
      if (JSON.stringify(placeholders(source[key])) !== JSON.stringify(placeholders(text))) throw new Error(`${locale}: placeholder mismatch for ${key}`);
      if (locale === 'en' && /[\u3400-\u9fff]/u.test(text)) throw new Error(`en: Chinese text in ${key}`);
      if (locale === 'ja' && text === source[key] && text.replace(/\{[a-zA-Z][\w]*\}/g, '').trim().length > 8 && /[\u3400-\u9fff]/u.test(text)) throw new Error(`ja: copied Chinese source in ${key}`);
    }
  }
  return keys;
}

export function generateAccessors(resources) {
  const keys = validateResources(resources);
  const parameters = keys.filter(key => placeholders(resources.zh[key]).length).map(key => `  ${JSON.stringify(key)}: { ${placeholders(resources.zh[key]).map(name => `${name}: string | number`).join('; ')} };`).join('\n');
  const parameterNames = Object.fromEntries(keys.filter(key => placeholders(resources.zh[key]).length).map(key => [key, placeholders(resources.zh[key])]));
  // Exact aliases only for application-authored API catalogs and historical server errors.
  // Page rendering uses resource identifiers directly; no DOM or template translation.
  const aliases = Object.fromEntries(keys.filter(key => !placeholders(resources.zh[key]).length).map(key => [resources.zh[key], key]));
  return `// Generated by npm run i18n:generate. Edit public/locales/*.json, then regenerate.\nimport zh from '../../public/locales/zh.json' with { type: 'json' };\nimport ja from '../../public/locales/ja.json' with { type: 'json' };\nimport en from '../../public/locales/en.json' with { type: 'json' };\nimport type { Locale } from '../locales.ts';\n\nexport type MessageKey = keyof typeof zh;\nexport type MessageParameters = {\n${parameters}\n};\nexport type MessageArgs<K extends MessageKey> = K extends keyof MessageParameters ? [params: MessageParameters[K]] : [params?: undefined];\nexport type BrowserMessageArgs<K extends MessageKey> = [...MessageArgs<K>, locale?: Locale];\nconst resources: Record<Locale, Record<MessageKey, string>> = { zh, ja, en };\nexport const parameterNames: Partial<Record<MessageKey, readonly string[]>> = ${serialize(parameterNames)};\nconst authoredKeys: Readonly<Record<string, MessageKey>> = ${serialize(aliases)};\nexport function authoredMessageKey(value: string): MessageKey | undefined {\n  return Object.hasOwn(zh, value) ? value as MessageKey : Object.hasOwn(authoredKeys, value) ? authoredKeys[value] : undefined;\n}\nexport function formatMessage<K extends MessageKey>(locale: Locale, key: K, ...args: MessageArgs<K>): string {\n  if (!Object.hasOwn(resources, locale) || !Object.hasOwn(resources[locale], key)) throw new Error('Unknown localization resource: ' + locale + '/' + key);\n  const params = args[0] as Record<string, string | number> | undefined;\n  const expected = parameterNames[key] ?? [];\n  if (expected.length !== Object.keys(params ?? {}).length || expected.some(name => !Object.hasOwn(params ?? {}, name))) throw new Error('Invalid localization parameters: ' + key);\n  return resources[locale][key].replace(/\\{([a-zA-Z][\\w]*)\\}/g, (_, name: string) => String(params![name]));\n}\n`;
}

async function checkCallSites(keys) {
  const failures = [];
  for (const file of (await readdir(join(root, 'public'))).filter(file => /\.(js|ts)$/.test(file))) {
    const source = await readFile(join(root, 'public', file), 'utf8');
    const ast = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true);
    function visit(node) {
      const line = ast.getLineAndCharacterOfPosition(node.getStart(ast)).line + 1;
      if ((ts.isStringLiteralLike(node) || ts.isTemplateLiteralToken(node)) && /[\u3400-\u9fff]/u.test(node.text)) failures.push(`${file}:${line}: UI text must reference a resource key`);
      if (ts.isCallExpression(node) && ts.isIdentifier(node.expression) && ['t', 'message'].includes(node.expression.text) && ts.isStringLiteralLike(node.arguments[0]) && !keys.includes(node.arguments[0].text)) failures.push(`${file}:${line}: unknown resource key`);
      ts.forEachChild(node, visit);
    }
    visit(ast);
  }
  if (failures.length) throw new Error(failures.join('\n'));
  const shell = await readFile(join(root, 'public/index.html'), 'utf8');
  if (/[\u3400-\u9fff]/u.test(shell)) throw new Error('index.html: authored text must use explicit resource bindings.');
  for (const match of shell.matchAll(/data-i18n(?:-[\w-]+)?="([^"]+)"/g)) if (!keys.includes(match[1])) throw new Error(`index.html: unknown resource ${match[1]}`);
}

export async function run(command = process.argv[2]) {
  if (!['generate', 'check'].includes(command)) throw new Error('Use npm run i18n:generate or npm run i18n:check. This CLI generates accessors only.');
  const resources = Object.fromEntries(await Promise.all(locales.map(async locale => [locale, JSON.parse(await readFile(join(root, 'public/locales', `${locale}.json`), 'utf8'))])));
  const keys = validateResources(resources), generated = generateAccessors(resources);
  const target = join(root, 'src/generated/localizations.ts');
  if (command === 'generate') await writeFile(target, generated);
  else if (await readFile(target, 'utf8') !== generated) throw new Error('Generated localizations are stale. Run npm run i18n:generate.');
  await checkCallSites(keys);
  console.log(`i18n ${command}: ${keys.length} resources, zh/ja/en, generated keys and parameters verified.`);
}
if (process.argv[1] === fileURLToPath(import.meta.url)) run().catch(error => { console.error(error.message); process.exitCode = 1; });
