import { createHash } from 'node:crypto';
import type { KnowledgePoint } from './study.ts';

export const BREADTH_DOMAINS = {
  patterns: '设计模式', architecture: '架构与系统设计', workflow: '开发方法与交付',
  flutter: 'Flutter / Dart 工程', jvm: 'Kotlin / Java / Android', apple: 'Swift / Apple 工程',
  web: 'Web / 前端工程', backend: '后端 / 数据工程', cloud: '云 / 基础设施', quality: '测试 / 可观测性',
} as const;
export const BREADTH_GROUPS = {
  design: '模式与架构', generation: '代码生成与构建', integration: '互操作与接口',
  testing: '测试与质量', delivery: '协作与交付', data: '数据与并发', operations: '运维与监控', security: '安全与权限',
} as const;
export type BreadthDomain = keyof typeof BREADTH_DOMAINS;
export type BreadthGroup = keyof typeof BREADTH_GROUPS;
export type BreadthScope = { domain: BreadthDomain | 'all'; group: BreadthGroup | 'all' };
type Entry = [BreadthGroup, string, string, string?];
const catalog: Record<BreadthDomain, Entry[]> = {
  patterns: [
    ['design','Strategy / 策略模式','同一业务有多种算法时，如何替换行为，何时简单函数就够用。'],
    ['design','Factory / 工厂方法 / Abstract Factory','比较创建一个对象与创建一组相关对象的需求。'],
    ['design','Builder / 建造者','复杂对象的分步构造、可选参数与构造函数的取舍。'],
    ['design','Adapter / 适配器','旧接口与新接口不一致时如何保持调用方稳定。'],
    ['design','Decorator / 装饰器','按需组合能力，与继承或修改原对象的差异。'],
    ['design','Observer / 观察者','通知、订阅生命周期、解订阅与重复事件。'],
    ['design','Facade / 外观','为复杂子系统提供简单入口，如何避免变成万能对象。'],
    ['design','Proxy / 代理','访问控制、延迟加载，与适配器和装饰器的区别。'],
    ['design','Command / 命令','把操作封装用于队列、撤销或日志的适用条件。'],
    ['design','State / 状态模式','状态转换与分支控制，区别于策略模式。'],
    ['design','Template Method / 模板方法','固定流程与可变步骤，比较继承与组合。'],
    ['design','Singleton / 单例的边界','全局状态、生命周期、依赖注入与可测试性。'],
    ['design','Composite / 组合模式','树形对象的统一操作与叶节点行为差异。'],
    ['design','Prototype / 原型模式','克隆已有对象与重新构建，比较浅拷贝、深拷贝和共享状态。'],
    ['design','Bridge / 桥接模式','两个变化维度分别演进时，比较桥接与适配器。'],
    ['design','Flyweight / 享元模式','共享大量相似对象的内在状态，说明外部状态与资源边界。'],
    ['design','Chain of Responsibility / 责任链','让多个处理器依次处理请求，说明顺序、短路和未处理情况。'],
    ['design','Iterator / 迭代器','不暴露内部结构地遍历集合，说明修改集合时的边界。'],
    ['design','Mediator / 中介者','降低多个对象间的交互耦合，以及中介对象膨胀的风险。'],
    ['design','Memento / 备忘录','保存恢复状态，比较快照、撤销命令与事件记录。'],
    ['design','Visitor / 访问者','对象结构稳定但操作变化时的选型，与增加节点类型的代价。'],
    ['design','Interpreter / 解释器','简单语法的解释、表达式树与成熟解析工具的取舍。'],
    ['design','DI / IoC / Service Locator','区分注入、控制反转、查找依赖和依赖倒置原则。'],
  ],
  architecture: [
    ['design','MVC / MVP / MVVM / MVI','区分职责和数据流，结合具体产品选型。'],
    ['design','Clean Architecture / Hexagonal Architecture','依赖方向、端口适配器、业务边界与过度分层。'],
    ['design','DDD / 聚合 / 限界上下文','区分业务建模、模块划分、聚合不变量与事务边界。'],
    ['design','CQRS / Event Sourcing','区分读写分离与事件存储，说明复杂度和适用条件。'],
    ['design','模块化单体 / 微服务','比较部署、团队边界、分布式代价与演进路径。'],
    ['integration','REST / GraphQL / gRPC','比较接口契约、数据需求、客户端与服务端协作成本。'],
    ['data','缓存 / 一致性 / 失效策略','缓存更新、过期、穿透和业务一致性边界。'],
    ['data','幂等 / 重试 / 超时','重复请求与部分失败，解释幂等键和重试边界。'],
    ['data','Outbox / Saga / 最终一致性','跨服务或消息发布时的事务边界与补偿。'],
    ['data','状态机 / 并发 / 取消','区分一次操作与长期状态，解释竞态和取消语义。'],
  ],
  workflow: [
    ['delivery','Scrum / Kanban / WIP','区分迭代规划与流动管理，说明在制品限制和实际约束。'],
    ['testing','TDD / BDD / ATDD','区分测试驱动、行为描述和验收协作，不混同测试层级。'],
    ['delivery','Trunk-Based / Git Flow','结合发布频率、分支生命周期和合并风险选用流程。'],
    ['delivery','CI / CD / 灰度 / Feature Flag','区分持续集成、交付与部署，说明回滚和功能开关。'],
    ['delivery','ADR / RFC / Code Review','记录决策、提议变更和审查反馈的不同目的。'],
    ['delivery','Monorepo / Polyrepo','多包共享、版本发布、构建范围和团队权限的取舍。'],
    ['delivery','Semantic Versioning / 锁文件','兼容性、依赖解析、可重复构建和升级验证。'],
    ['operations','Incident / Postmortem / Runbook','区分应急处置、事后复盘和可执行排障步骤。'],
  ],
  flutter: [
    ['generation','build_runner / source_gen','区分生成任务运行器、生成器和产物，处理冲突与构建范围。'],
    ['generation','Freezed / json_serializable','区分不可变数据模型、联合类型和 JSON 序列化的职责。'],
    ['generation','Riverpod generator / injectable','比较状态或依赖相关生成器的用途与所依赖的运行时。'],
    ['delivery','Melos / Dart Pub Workspaces','Dart 多包仓库的依赖工作区、任务、版本和发布管理；不把它当成任意库的替代品。','https://melos.invertase.dev/'],
    ['integration','Pigeon / Platform Channels','Pigeon 为 Flutter 与宿主平台通信生成类型安全绑定；比较手写 MethodChannel 的契约成本。','https://github.com/flutter/packages/tree/main/packages/pigeon'],
    ['integration','Dart FFI / 原生插件','比较调用 C ABI 与宿主平台消息通信的适用边界。'],
    ['testing','flutter_test / integration_test / Golden Test','区分单元、Widget、端到端和图像回归测试。'],
    ['testing','Mocktail / Mockito / Fake','依赖替身、生成与手写策略，以及过度 mock 的风险。'],
    ['design','BLoC / Riverpod / 状态管理','比较状态、事件、依赖、生命周期与业务边界。'],
    ['operations','Flutter DevTools / 性能与内存','结合卡顿、重建、内存和网络问题选择诊断视图。'],
    ['data','Isolate / compute / 异步 I/O','区分异步等待与 CPU 并行，以及消息传递开销。'],
  ],
  jvm: [
    ['generation','KSP / kapt / 编译器插件','比较符号处理、注解处理与编译器插件；说明处理器兼容性。','https://kotlinlang.org/docs/ksp-overview.html'],
    ['generation','KotlinPoet / JavaPoet','区分源代码生成库与运行生成器的处理框架。'],
    ['generation','Gradle / Convention Plugins / Version Catalog','多模块构建约定、插件复用与依赖版本管理。'],
    ['design','Dagger / Hilt / Koin','比较依赖注入方案、作用域、编译时验证和测试替换。'],
    ['integration','Retrofit / OkHttp / Ktor','区分声明式接口、HTTP 客户端和客户端/服务端框架。'],
    ['data','Room / DataStore / SQLDelight','区分结构化数据库、偏好数据和 SQL 驱动代码生成。'],
    ['data','Coroutines / Flow / StateFlow','结构化并发、冷/热流、生命周期与取消。'],
    ['testing','JUnit / MockK / Robolectric / Espresso','比较 JVM 单元、模拟 Android 环境和设备 UI 测试。'],
    ['testing','Compose UI Test / Macrobenchmark / Baseline Profiles','区分 UI 验证、性能度量和运行时优化产物。'],
    ['integration','Kotlin Multiplatform / 平台边界','共享业务逻辑、原生能力与平台差异。'],
    ['operations','R8 / mapping / ANR / Profiler','压缩混淆、堆栈还原、线程阻塞与性能定位。'],
  ],
  apple: [
    ['generation','Swift Macros / Sourcery','比较编译期宏与源代码生成的输入和构建边界。'],
    ['generation','SwiftGen / 资源类型安全','资源访问生成、命名与资源变更后的构建同步。'],
    ['delivery','Swift Package Manager / CocoaPods','区分包依赖、构建集成和迁移约束。'],
    ['generation','Tuist / XcodeGen','项目文件生成、构建配置与团队一致性。'],
    ['testing','Swift Testing / XCTest / XCUITest','区分测试框架、单元测试和 UI 自动化。'],
    ['design','Combine / async-await / Actors','区分流式处理、异步调用与数据隔离。'],
    ['operations','Instruments / dSYM / 符号化','结合 CPU、内存、能耗和崩溃堆栈选择工具。'],
    ['delivery','fastlane / 签名 / TestFlight','构建发布自动化与证书、描述文件的职责。'],
  ],
  web: [
    ['generation','Vite / webpack / esbuild','区分开发服务、打包和代码转换的职责。'],
    ['delivery','pnpm Workspaces / Nx / Turborepo','包工作区、任务图、缓存和 Monorepo 管理。'],
    ['generation','OpenAPI Generator / GraphQL Code Generator','按接口契约生成客户端或类型，说明契约变更风险。'],
    ['testing','Vitest / Jest / Testing Library','测试运行器、断言与面向用户行为的组件测试。'],
    ['testing','Playwright / Cypress / MSW','浏览器端到端测试与网络请求模拟的边界。'],
    ['testing','ESLint / Prettier / TypeScript','区分静态规则、格式与类型检查。'],
    ['design','CSR / SSR / SSG / Hydration','页面渲染、交互恢复、缓存与部署取舍。'],
    ['data','状态管理 / 服务端状态 / 缓存','区分客户端交互状态与远程数据同步。'],
    ['security','CORS / CSP / XSS / CSRF','区分跨域策略、内容策略和攻击条件。'],
  ],
  backend: [
    ['generation','Go generate / sqlc / Protocol Buffers','区分生成任务入口、SQL 类型代码和接口序列化。'],
    ['delivery','Python venv / uv / Poetry','隔离环境、依赖解析、锁定和项目管理。'],
    ['testing','pytest / Go test / JUnit','跨语言测试组织、参数化与集成环境。'],
    ['testing','Testcontainers / 契约测试','真实依赖集成环境与消费者/提供者契约验证。'],
    ['data','Flyway / Liquibase / Alembic','数据库迁移、版本演进与回滚限制。'],
    ['data','ORM / SQL / Query Plan','抽象效率、N+1、索引和执行计划。'],
    ['data','Redis / Kafka / RabbitMQ','缓存、事件流和消息队列的职责及交付语义。'],
    ['integration','OpenAPI / Protobuf / API 版本','接口契约、兼容性和客户端演进。'],
    ['security','OAuth / OIDC / JWT','区分授权、认证与令牌格式。'],
    ['data','事务隔离 / 乐观锁 / 悲观锁','结合并发更新和一致性要求选择控制策略。'],
  ],
  cloud: [
    ['generation','Terraform / Provider / State / Plan','Terraform 是跨平台 IaC 工具，AWS Provider 管理 AWS 资源；区分配置、状态、计划与执行。','https://developer.hashicorp.com/terraform/docs'],
    ['generation','CloudFormation / AWS CDK / Pulumi','比较基础设施声明与编程式建模，不把 Terraform 说成 AWS 服务。'],
    ['delivery','Docker / 多阶段构建 / 镜像','区分镜像与容器，说明依赖、构建和运行环境。'],
    ['operations','Kubernetes / Helm / Kustomize','区分容器编排、模板打包和配置覆盖。'],
    ['delivery','Argo CD / GitOps','声明式交付、漂移检测、同步和回滚边界。'],
    ['security','AWS IAM / 最小权限 / Secrets','身份、角色、权限边界与凭据管理。'],
    ['design','EC2 / ECS / EKS / Lambda','结合运行时、伸缩、运维和成本选择计算形态。'],
    ['data','S3 / RDS / DynamoDB','结合访问模式、查询、对象与事务需求选用存储。'],
    ['integration','VPC / 子网 / NAT / 负载均衡','解释网络隔离、出站访问与流量分配的角色。'],
    ['operations','CloudWatch / CloudTrail','区分运维遥测与账号操作审计。'],
    ['operations','基础设施漂移 / State 锁 / 回滚','多人协作、计划审查与不可逆变更边界。'],
  ],
  quality: [
    ['testing','测试金字塔 / 单元 / 集成 / E2E','测试成本、反馈速度与代表性，避免只追求覆盖率。'],
    ['testing','Mock / Stub / Fake / Test Double','区分依赖替身行为、断言范围与脆弱测试。'],
    ['testing','Property-Based / Mutation Testing','生成输入验证性质与变异代码检验测试有效性。'],
    ['testing','k6 / JMeter / 性能测试','区分吞吐、延迟、负载、压力与长时间运行。'],
    ['operations','Logs / Metrics / Traces / OpenTelemetry','区分日志、指标、链路与遥测采集标准。'],
    ['operations','Prometheus / Grafana','区分度量采集查询与展示告警。'],
    ['operations','Sentry / Crashlytics / Datadog','错误、崩溃、RUM、APM 的范围、上下文与排查流程。'],
    ['operations','SLI / SLO / Error Budget','用户体验指标、目标与错误预算的关系。'],
    ['operations','移动端 Crash / ANR / dSYM / mapping','区分崩溃、无响应、符号化和混淆还原。'],
    ['security','SAST / DAST / 依赖扫描 / SBOM','区分代码、运行态、依赖风险和软件物料清单。'],
  ],
};
export const BREADTH_POINTS: KnowledgePoint[] = Object.entries(catalog).flatMap(([domain, entries]) => entries.map(([group, title, description, url]) => ({
  id: `breadth-${createHash('sha256').update(`${domain}|${title}`).digest('hex').slice(0,20)}`,
  title, description, category: (['generation','integration','operations'].includes(group) ? 'tools' : 'concept') as KnowledgePoint['category'],
  topic: BREADTH_DOMAINS[domain as BreadthDomain], facets: ['recall','apply','explain'],
  breadth: { domain: domain as BreadthDomain, group },
  ...(url ? { references: [{ title: `${title.split(' / ')[0]} 官方资料`, url }] } : {}),
})));
