import { formatMessage } from './generated/localizations.ts';
import { createHash } from 'node:crypto';
import type { KnowledgePoint } from './study.ts';

export const BREADTH_DOMAINS = {
  patterns: formatMessage('zh', "ui.designPatterns"), architecture: formatMessage('zh', "ui.architectureAndSystemDesign"), workflow: formatMessage('zh', "ui.developmentMethodsAndDelivery"),
  flutter: formatMessage('zh', "ui.flutterDartEngineering"), jvm: 'Kotlin / Java / Android', apple: formatMessage('zh', "ui.swiftAppleEngineering"),
  web: formatMessage('zh', "ui.webFrontendEngineering"), backend: formatMessage('zh', "ui.backendDataEngineering"), cloud: formatMessage('zh', "ui.cloudInfrastructure"), quality: formatMessage('zh', "ui.testingObservability"),
} as const;
export const BREADTH_GROUPS = {
  design: formatMessage('zh', "ui.patternsAndArchitecture"), generation: formatMessage('zh', "ui.codeGenerationAndBuilds"), integration: formatMessage('zh', "ui.interoperabilityAndInterfaces"),
  testing: formatMessage('zh', "ui.testingAndQuality"), delivery: formatMessage('zh', "ui.collaborationAndDelivery"), data: formatMessage('zh', "ui.dataAndConcurrency"), operations: formatMessage('zh', "ui.operationsAndMonitoring"), security: formatMessage('zh', "ui.securityAndPermissions"),
} as const;
export type BreadthDomain = keyof typeof BREADTH_DOMAINS;
export type BreadthGroup = keyof typeof BREADTH_GROUPS;
export type BreadthScope = { domain: BreadthDomain | 'all'; group: BreadthGroup | 'all' };
type Entry = [BreadthGroup, string, string, string?];
const catalog: Record<BreadthDomain, Entry[]> = {
  patterns: [
    ['design',formatMessage('zh', "ui.strategyStrategyPattern"),formatMessage('zh', "ui.whenTheSameBusinessCaseHasMultipleAlgorithms")],
    ['design',formatMessage('zh', "ui.factoryFactoryMethodAbstractFactory"),formatMessage('zh', "ui.compareTheNeedToCreateOneObjectWith")],
    ['design',formatMessage('zh', "ui.builderBuilderPattern"),formatMessage('zh', "ui.stepByStepConstructionOfComplexObjectsOptional")],
    ['design',formatMessage('zh', "ui.adapterAdapterPattern"),formatMessage('zh', "ui.howToKeepCallersStableWhenOldAnd")],
    ['design',formatMessage('zh', "ui.decoratorDecoratorPattern"),formatMessage('zh', "ui.composeCapabilitiesOnDemandAndCompareThatWith")],
    ['design',formatMessage('zh', "ui.observerObserverPattern"),formatMessage('zh', "ui.notificationsSubscriptionLifecycleUnsubscribeAndDuplicateEvents")],
    ['design',formatMessage('zh', "ui.facadeFacadePattern"),formatMessage('zh', "ui.provideASimpleEntryPointForAComplex")],
    ['design',formatMessage('zh', "ui.proxyProxyPattern"),formatMessage('zh', "ui.accessControlLazyLoadingAndHowTheyDiffer")],
    ['design',formatMessage('zh', "ui.commandCommandPattern"),formatMessage('zh', "ui.whenEncapsulatingOperationsIsSuitableForQueuesUndo")],
    ['design',formatMessage('zh', "ui.stateStatePattern"),formatMessage('zh', "ui.stateTransitionsAndBranchControlDistinctFromThe")],
    ['design',formatMessage('zh', "ui.templateMethodTemplateMethodPattern"),formatMessage('zh', "ui.fixedFlowAndVariableStepsCompareInheritanceWith")],
    ['design',formatMessage('zh', "ui.singletonSingletonBoundaries"),formatMessage('zh', "ui.globalStateLifecycleDependencyInjectionAndTestability")],
    ['design',formatMessage('zh', "ui.compositeCompositePattern"),formatMessage('zh', "ui.unifiedOperationsOnTreeLikeObjectsAndDifferences")],
    ['design',formatMessage('zh', "ui.prototypePrototypePattern"),formatMessage('zh', "ui.cloneAnExistingObjectVersusRebuildItComparing")],
    ['design',formatMessage('zh', "ui.bridgeBridgePattern"),formatMessage('zh', "ui.compareBridgeAndAdapterWhenTwoDimensionsOf")],
    ['design',formatMessage('zh', "ui.flyweightFlyweightPattern"),formatMessage('zh', "ui.shareIntrinsicStateAcrossManySimilarObjectsAnd")],
    ['design',formatMessage('zh', "ui.chainOfResponsibilityChainOfResponsibilityPattern"),formatMessage('zh', "ui.letMultipleHandlersProcessRequestsInSequenceAnd")],
    ['design',formatMessage('zh', "ui.iteratorIteratorPattern"),formatMessage('zh', "ui.traverseACollectionWithoutExposingItsInternalStructure")],
    ['design',formatMessage('zh', "ui.mediatorMediatorPattern"),formatMessage('zh', "ui.reduceInteractionCouplingBetweenMultipleObjectsAndWatch")],
    ['design',formatMessage('zh', "ui.mementoMementoPattern"),formatMessage('zh', "ui.saveAndRestoreStateComparingSnapshotsUndoCommands")],
    ['design',formatMessage('zh', "ui.visitorVisitor"),formatMessage('zh', "ui.choosingAnApproachWhenTheObjectStructureIs")],
    ['design',formatMessage('zh', "ui.interpreterInterpreterPattern"),formatMessage('zh', "ui.tradeOffsBetweenInterpretingSimpleSyntaxExpressionTrees")],
    ['design','DI / IoC / Service Locator',formatMessage('zh', "ui.distinguishInjectionInversionOfControlDependencyLookupAnd")],
  ],
  architecture: [
    ['design','MVC / MVP / MVVM / MVI',formatMessage('zh', "ui.distinguishResponsibilitiesAndDataFlowAndChooseBased")],
    ['design','Clean Architecture / Hexagonal Architecture',formatMessage('zh', "ui.dependencyDirectionPortsAndAdaptersBusinessBoundariesAnd")],
    ['design',formatMessage('zh', "ui.dDDAggregatesBoundedContexts"),formatMessage('zh', "ui.distinguishBusinessModelingModuleBoundariesAggregateInvariantsAnd")],
    ['design','CQRS / Event Sourcing',formatMessage('zh', "ui.distinguishReadWriteSeparationFromEventSourcingAnd")],
    ['design',formatMessage('zh', "ui.modularMonolithMicroservices"),formatMessage('zh', "ui.compareDeploymentTeamBoundariesDistributedSystemCostsAnd")],
    ['integration','REST / GraphQL / gRPC',formatMessage('zh', "ui.compareInterfaceContractsDataNeedsAndClientServer")],
    ['data',formatMessage('zh', "ui.cacheConsistencyInvalidationStrategy"),formatMessage('zh', "ui.cacheUpdatesExpirationPenetrationAndBusinessConsistencyBoundaries")],
    ['data',formatMessage('zh', "ui.idempotencyRetryTimeout"),formatMessage('zh', "ui.forDuplicateRequestsAndPartialFailuresExplainIdempotency")],
    ['data',formatMessage('zh', "ui.outboxSagaEventualConsistency"),formatMessage('zh', "ui.transactionBoundariesAndCompensationAcrossServicesOrMessage")],
    ['data',formatMessage('zh', "ui.stateMachineConcurrencyCancellation"),formatMessage('zh', "ui.distinguishOneTimeOperationsFromLongLivedState")],
  ],
  workflow: [
    ['delivery','Scrum / Kanban / WIP',formatMessage('zh', "ui.distinguishIterationPlanningFromFlowManagementAndExplain")],
    ['testing','TDD / BDD / ATDD',formatMessage('zh', "ui.distinguishTestDrivenDevelopmentBehaviorDescriptionAndAcceptance")],
    ['delivery','Trunk-Based / Git Flow',formatMessage('zh', "ui.chooseAWorkflowBasedOnReleaseFrequencyBranch")],
    ['delivery',formatMessage('zh', "ui.cICDCanaryReleaseFeatureFlag"),formatMessage('zh', "ui.distinguishContinuousIntegrationDeliveryAndDeploymentAndExplain")],
    ['delivery','ADR / RFC / Code Review',formatMessage('zh', "ui.recordTheDifferentPurposesOfDecisionsProposedChanges")],
    ['delivery','Monorepo / Polyrepo',formatMessage('zh', "ui.tradeOffsInSharingMultiplePackagesVersionReleases")],
    ['delivery',formatMessage('zh', "ui.semanticVersioningLockFiles"),formatMessage('zh', "ui.compatibilityDependencyResolutionReproducibleBuildsAndUpgradeValidation")],
    ['operations','Incident / Postmortem / Runbook',formatMessage('zh', "ui.distinguishIncidentResponsePostmortemsAndExecutableTroubleshootingSteps")],
  ],
  flutter: [
    ['generation','build_runner / source_gen',formatMessage('zh', "ui.distinguishGeneratedTaskRunnersGeneratorsAndArtifactsAnd")],
    ['generation','Freezed / json_serializable',formatMessage('zh', "ui.distinguishTheResponsibilitiesOfImmutableDataModelsUnion")],
    ['generation','Riverpod generator / injectable',formatMessage('zh', "ui.compareThePurposesOfStateOrDependencyRelated")],
    ['delivery','Melos / Dart Pub Workspaces',formatMessage('zh', "ui.dependencyWorkspacesTasksVersioningAndReleaseManagementFor"),'https://melos.invertase.dev/'],
    ['integration','Pigeon / Platform Channels',formatMessage('zh', "ui.pigeonGeneratesTypeSafeBindingsForCommunicationBetween"),'https://github.com/flutter/packages/tree/main/packages/pigeon'],
    ['integration',formatMessage('zh', "ui.dartFFINativePlugins"),formatMessage('zh', "ui.compareTheApplicableBoundariesOfCallingAC")],
    ['testing','flutter_test / integration_test / Golden Test',formatMessage('zh', "ui.distinguishUnitWidgetEndToEndAndVisual")],
    ['testing','Mocktail / Mockito / Fake',formatMessage('zh', "ui.testDoublesGeneratedAndHandwrittenStrategiesAndThe")],
    ['design',formatMessage('zh', "ui.bLoCRiverpodStateManagement"),formatMessage('zh', "ui.compareStateEventsDependenciesLifecycleAndBusinessBoundaries")],
    ['operations',formatMessage('zh', "ui.flutterDevToolsPerformanceAndMemory"),formatMessage('zh', "ui.chooseDiagnosticViewsBasedOnJankRebuildsMemory")],
    ['data',formatMessage('zh', "ui.isolateComputeAsynchronousIO"),formatMessage('zh', "ui.distinguishAsyncWaitingFromCPUParallelismAndAccount")],
  ],
  jvm: [
    ['generation',formatMessage('zh', "ui.kSPKaptCompilerPlugins"),formatMessage('zh', "ui.compareSymbolProcessingAnnotationProcessingAndCompilerPlugins"),'https://kotlinlang.org/docs/ksp-overview.html'],
    ['generation','KotlinPoet / JavaPoet',formatMessage('zh', "ui.distinguishSourceCodeGenerationLibrariesFromProcessingFrameworks")],
    ['generation','Gradle / Convention Plugins / Version Catalog',formatMessage('zh', "ui.multiModuleBuildConventionsPluginReuseAndDependency")],
    ['design','Dagger / Hilt / Koin',formatMessage('zh', "ui.compareDependencyInjectionOptionsScopesCompileTimeValidation")],
    ['integration','Retrofit / OkHttp / Ktor',formatMessage('zh', "ui.distinguishDeclarativeInterfacesHTTPClientsAndClientServer")],
    ['data','Room / DataStore / SQLDelight',formatMessage('zh', "ui.distinguishStructuredDatabasesPreferenceDataAndSQLDriven")],
    ['data','Coroutines / Flow / StateFlow',formatMessage('zh', "ui.structuredConcurrencyColdHotFlowsLifecycleAndCancellation")],
    ['testing','JUnit / MockK / Robolectric / Espresso',formatMessage('zh', "ui.compareJVMUnitTestsSimulatedAndroidEnvironmentsAnd")],
    ['testing','Compose UI Test / Macrobenchmark / Baseline Profiles',formatMessage('zh', "ui.distinguishUIValidationPerformanceMeasurementAndRuntimeOptimization")],
    ['integration',formatMessage('zh', "ui.kotlinMultiplatformPlatformBoundaries"),formatMessage('zh', "ui.sharedBusinessLogicNativeCapabilitiesAndPlatformDifferences")],
    ['operations','R8 / mapping / ANR / Profiler',formatMessage('zh', "ui.minificationAndObfuscationStackTraceRecoveryThreadBlocking")],
  ],
  apple: [
    ['generation','Swift Macros / Sourcery',formatMessage('zh', "ui.compareTheInputsAndBuildBoundariesOfCompile")],
    ['generation',formatMessage('zh', "ui.swiftGenTypeSafeResources"),formatMessage('zh', "ui.resourceAccessGenerationNamingAndBuildSynchronizationAfter")],
    ['delivery','Swift Package Manager / CocoaPods',formatMessage('zh', "ui.distinguishPackageDependenciesBuildIntegrationAndMigrationConstraints")],
    ['generation','Tuist / XcodeGen',formatMessage('zh', "ui.projectFileGenerationBuildConfigurationAndTeamConsistency")],
    ['testing','Swift Testing / XCTest / XCUITest',formatMessage('zh', "ui.distinguishTestFrameworksUnitTestsAndUIAutomation")],
    ['design','Combine / async-await / Actors',formatMessage('zh', "ui.distinguishStreamProcessingAsynchronousCallsAndDataIsolation")],
    ['operations',formatMessage('zh', "ui.instrumentsDSYMSymbolication"),formatMessage('zh', "ui.chooseToolsBasedOnCPUMemoryEnergyUse")],
    ['delivery',formatMessage('zh', "ui.fastlaneSigningTestFlight"),formatMessage('zh', "ui.responsibilitiesForBuildAndReleaseAutomationCertificatesAnd")],
  ],
  web: [
    ['generation','Vite / webpack / esbuild',formatMessage('zh', "ui.distinguishTheResponsibilitiesOfDevServersBundlingAnd")],
    ['delivery','pnpm Workspaces / Nx / Turborepo',formatMessage('zh', "ui.packageWorkspacesTaskGraphsCachingAndMonorepoManagement")],
    ['generation','OpenAPI Generator / GraphQL Code Generator',formatMessage('zh', "ui.generateClientsOrTypesFromTheAPIContract")],
    ['testing','Vitest / Jest / Testing Library',formatMessage('zh', "ui.testRunnersAssertionsAndComponentTestsFocusedOn")],
    ['testing','Playwright / Cypress / MSW',formatMessage('zh', "ui.boundariesBetweenBrowserE2ETestingAndNetworkRequest")],
    ['testing','ESLint / Prettier / TypeScript',formatMessage('zh', "ui.distinguishStaticRulesFormattingAndTypeChecking")],
    ['design','CSR / SSR / SSG / Hydration',formatMessage('zh', "ui.tradeOffsInPageRenderingInteractionRecoveryCaching")],
    ['data',formatMessage('zh', "ui.stateManagementServerStateCache"),formatMessage('zh', "ui.distinguishClientInteractionStateFromRemoteDataSynchronization")],
    ['security','CORS / CSP / XSS / CSRF',formatMessage('zh', "ui.distinguishCrossOriginPolicyContentPolicyAndAttack")],
  ],
  backend: [
    ['generation','Go generate / sqlc / Protocol Buffers',formatMessage('zh', "ui.distinguishGeneratedTaskEntryPointsSQLTypedCode")],
    ['delivery','Python venv / uv / Poetry',formatMessage('zh', "ui.environmentIsolationDependencyResolutionLockingAndProjectManagement")],
    ['testing','pytest / Go test / JUnit',formatMessage('zh', "ui.crossLanguageTestOrganizationParameterizationAndIntegrationEnvironments")],
    ['testing',formatMessage('zh', "ui.testcontainersContractTesting"),formatMessage('zh', "ui.integrationEnvironmentsWithRealDependenciesAndConsumerProvider")],
    ['data','Flyway / Liquibase / Alembic',formatMessage('zh', "ui.databaseMigrationVersionEvolutionAndRollbackLimits")],
    ['data','ORM / SQL / Query Plan',formatMessage('zh', "ui.abstractionEfficiencyNIndexesAndExecutionPlans")],
    ['data','Redis / Kafka / RabbitMQ',formatMessage('zh', "ui.responsibilitiesAndDeliverySemanticsOfCachesEventStreams")],
    ['integration',formatMessage('zh', "ui.openAPIProtobufAPIVersions"),formatMessage('zh', "ui.aPIContractsCompatibilityAndClientEvolution")],
    ['security','OAuth / OIDC / JWT',formatMessage('zh', "ui.distinguishAuthorizationAuthenticationAndTokenFormats")],
    ['data',formatMessage('zh', "ui.transactionIsolationOptimisticLockingPessimisticLocking"),formatMessage('zh', "ui.chooseAControlStrategyBasedOnConcurrentUpdates")],
  ],
  cloud: [
    ['generation','Terraform / Provider / State / Plan',formatMessage('zh', "ui.terraformIsACrossPlatformIaCToolAnd"),'https://developer.hashicorp.com/terraform/docs'],
    ['generation','CloudFormation / AWS CDK / Pulumi',formatMessage('zh', "ui.compareInfrastructureDeclarationsAndProgrammaticModelingAndDo")],
    ['delivery',formatMessage('zh', "ui.dockerMultiStageBuildsImages"),formatMessage('zh', "ui.distinguishImagesFromContainersAndExplainDependenciesBuild")],
    ['operations','Kubernetes / Helm / Kustomize',formatMessage('zh', "ui.distinguishContainerOrchestrationTemplatePackagingAndConfigurationOverrides")],
    ['delivery','Argo CD / GitOps',formatMessage('zh', "ui.declarativeDeliveryDriftDetectionSynchronizationAndRollbackBoundaries")],
    ['security',formatMessage('zh', "ui.aWSIAMLeastPrivilegeSecrets"),formatMessage('zh', "ui.identityRolesPermissionBoundariesAndCredentialManagement")],
    ['design','EC2 / ECS / EKS / Lambda',formatMessage('zh', "ui.chooseAComputeModelBasedOnRuntimeScaling")],
    ['data','S3 / RDS / DynamoDB',formatMessage('zh', "ui.chooseStorageBasedOnAccessPatternsQueriesObjects")],
    ['integration',formatMessage('zh', "ui.vPCSubnetNATLoadBalancing"),formatMessage('zh', "ui.explainTheRolesOfNetworkIsolationOutboundAccess")],
    ['operations','CloudWatch / CloudTrail',formatMessage('zh', "ui.distinguishOperationsTelemetryFromAccountOperationAuditing")],
    ['operations',formatMessage('zh', "ui.infrastructureDriftStateLockRollback"),formatMessage('zh', "ui.teamCollaborationPlanReviewAndBoundariesForIrreversible")],
  ],
  quality: [
    ['testing',formatMessage('zh', "ui.testingPyramidUnitIntegrationE2E"),formatMessage('zh', "ui.balanceTestCostFeedbackSpeedAndRepresentativenessAvoid")],
    ['testing','Mock / Stub / Fake / Test Double',formatMessage('zh', "ui.distinguishTestDoubleBehaviorAssertionScopeAndBrittle")],
    ['testing','Property-Based / Mutation Testing',formatMessage('zh', "ui.generateInputsToVerifyPropertiesAndUseMutated")],
    ['testing',formatMessage('zh', "ui.k6JMeterPerformanceTesting"),formatMessage('zh', "ui.distinguishThroughputLatencyLoadStressAndLongRunning")],
    ['operations','Logs / Metrics / Traces / OpenTelemetry',formatMessage('zh', "ui.distinguishLogsMetricsTracesAndTelemetryCollectionStandards")],
    ['operations','Prometheus / Grafana',formatMessage('zh', "ui.distinguishMetricCollectionQueriesFromDisplayAndAlerting")],
    ['operations','Sentry / Crashlytics / Datadog',formatMessage('zh', "ui.scopeContextAndTroubleshootingFlowForErrorsCrashes")],
    ['operations','SLI / SLO / Error Budget',formatMessage('zh', "ui.theRelationshipBetweenUserExperienceIndicatorsObjectivesAnd")],
    ['operations',formatMessage('zh', "ui.mobileCrashANRDSYMMapping"),formatMessage('zh', "ui.distinguishCrashesHangsSymbolicationAndDeobfuscation")],
    ['security',formatMessage('zh', "ui.sASTDASTDependencyScanningSBOM"),formatMessage('zh', "ui.distinguishCodeRuntimeBehaviorDependencyRiskAndSoftware")],
  ],
};
export const BREADTH_POINTS: KnowledgePoint[] = Object.entries(catalog).flatMap(([domain, entries]) => entries.map(([group, title, description, url]) => ({
  id: `breadth-${createHash('sha256').update(`${domain}|${title}`).digest('hex').slice(0,20)}`,
  title, description, category: (['generation','integration','operations'].includes(group) ? 'tools' : 'concept') as KnowledgePoint['category'],
  topic: BREADTH_DOMAINS[domain as BreadthDomain], facets: ['recall','apply','explain'],
  breadth: { domain: domain as BreadthDomain, group },
  ...(url ? { references: [{ title: `${title.split(' / ')[0]} 官方资料`, url }] } : {}),
})));
