/** Wire contracts. CLI generators consume these types; business rules stay with their owners. */
import type { State, Selection, ProblemContent, Hint, ReviewContent, AnalysisContent, TeacherSettings, InterviewMaterials, Language, statistics, TOPICS, DIFFICULTIES, LANGUAGES } from './domain.ts';
import type { Locale } from './locales.ts';
import type { LanguageSelection, LanguageDrill, DrillContent, LANGUAGE_SYLLABUS } from './language.ts';
import type { InterviewSelection, InterviewJob, Question, InterviewContent, InterviewReviewContent, VoiceContent, publicInterview, INTERVIEW_TYPES, INTERVIEW_TOPICS, jobInput } from './interview.ts';
import type { LibraryItem, librarySummary, libraryMetadata, libraryEdit } from './library.ts';
import type { Chat, ChatThread, ChatTurn, PageContext } from './chat.ts';
import type { Study, StudySelection, KnowledgePoint, Facet, Feedback, Reference, publicBatch, STUDY_CATEGORIES, STUDY_FACETS } from './study.ts';
import type { TrainingKind, CompressionResult, FollowupResult, DiagnosisResult, DebriefResult, Scenario, publicTraining, DIAGNOSIS_TOPICS, TRAINING_KINDS } from './training.ts';
import type { AI, ModelOption } from './pi.ts';
import type { CodexVoice, VoiceTranscript } from './codex-voice.ts';
import type { VoiceInterviews, InterviewProgress } from './voice-interview.ts';
import type { VoiceSettings } from './voice-options.ts';
import type { InterviewSources } from './interview-sources.ts';
import type { Job } from './tasks.ts';
import type { NativeContracts } from './codex-protocol.ts';

export type BackupArchive = { format: 'recruitagent-backup'; version: 1; createdAt: string; state: State; stateHash: string; files: { name: string; hash: string; data: string }[] };
export type TaskResult = { problemId?: string; drillId?: string; interviewId?: string; trainingId?: string; batchId?: string; chatId?: string; turnId?: string; reviewId?: string; hintId?: string; created?: boolean; libraryIds?: string[]; failedIds?: string[]; pointIds?: string[]; count?: number; reviewed?: number; analysis?: boolean };
export type JobInfo = Pick<Job, 'id' | 'kind' | 'status' | 'error'> & { result?: TaskResult };
export type ActiveJob = Pick<Job, 'id' | 'kind' | 'chatId'> | null;
export type PublicState = Omit<State, 'chats' | 'interviews' | 'library' | 'trainings' | 'studyBatches'> & {
  interviews: ReturnType<typeof publicInterview>[]; library: ReturnType<typeof librarySummary>[];
  trainings: ReturnType<typeof publicTraining>[]; studyBatches: ReturnType<typeof publicBatch>[];
  languageDrills: LanguageDrill[]; interviewJobs: InterviewJob[]; study: ReturnType<Study['overview']>;
  stats: ReturnType<typeof statistics>; analysisStale: boolean; activeJob: ActiveJob; reviewLabel: string;
};
export type Settings = { model: string; visibleModels: string[]; teacher: TeacherSettings; uiLanguage: Locale; userLanguage: Locale };
export type Config = {
  studyCategories: typeof STUDY_CATEGORIES; studyFacets: typeof STUDY_FACETS;
  trainingKinds: typeof TRAINING_KINDS; diagnosisTopics: typeof DIAGNOSIS_TOPICS;
  topics: typeof TOPICS; difficulties: typeof DIFFICULTIES; languages: typeof LANGUAGES;
  models: readonly ModelOption[]; libraryLimit: number; languageSyllabus: typeof LANGUAGE_SYLLABUS;
  interviewTypes: typeof INTERVIEW_TYPES; interviewTopics: typeof INTERVIEW_TOPICS;
  interviewSources: Awaited<ReturnType<InterviewSources['status']>>;
};
export type ChatInput = { id: string; message: string; context: Omit<PageContext, 'capturedAt' | 'record'> & { capturedAt?: string } };
export type TeacherInput = { id: string; code: string; trigger: 'observe' | 'check' | 'question'; revision: number; message?: string };
export type CodeInput = { /** @maxLength 100000 */ code: string };
export type AnswersInput = { answers: Record<string, string> };
export type DraftInput = { draft: Record<string, string> };
export type TaskStarted = { jobId: string; chatId?: string };
export type EmptyInput = Record<string, never>;
export type VoiceStartInput = Partial<VoiceSettings> & { id: string; sdp: string; interviewId?: string; preview?: boolean; synthetic?: boolean };
export type VoiceActionInput = { action: 'begin' | 'next' | 'retry' | 'finish' | 'answer-started' | 'response-complete'; roundAt?: string; inputRevision?: number };
export type VoiceControlInput = { action: 'stop' | 'pause' | 'resume' };
export type VoiceDiagnosticInput = {
  event: 'state' | 'transport' | 'response' | 'error' | 'verification';
  phase?: string; type?: string; responseId?: string; code?: string; message?: string;
  recording?: boolean; processing?: boolean; backendThinking?: boolean; paused?: boolean;
  outputSpeaking?: boolean; audioVerified?: boolean; revision?: number; inputRevision?: number;
};
export type LibraryDetail = ReturnType<typeof librarySummary> & { extractedText: string; pages?: Omit<NonNullable<LibraryItem['pages']>[number], 'text'>[] };
type Endpoint<B, R> = { body: B; response: R };
type Read<R> = { response: R };
type Saved = { saved: boolean };
type Ok = { ok: boolean };

/** Method + path is the authority for both runtime matching and OpenAPI generation. */
export interface ApiEndpoints {
  'GET /api/health': Read<{ ok: boolean; app: string }>;
  'GET /api/state': Read<PublicState>;
  'GET /api/config': Read<Config>;
  'GET /api/settings': Read<Settings>;
  'PUT /api/settings': Endpoint<Partial<Omit<Settings, 'model'>>, Settings>;
  'PUT /api/model': Endpoint<{ model: string }, Awaited<ReturnType<AI['status']>>>;
  'GET /api/auth/status': Read<Awaited<ReturnType<AI['status']>>>;
  'POST /api/auth/login': Endpoint<EmptyInput, { id: string }>;
  'POST /api/auth/cancel': Endpoint<EmptyInput, Ok>;
  'POST /api/auth/{id}/answer': Endpoint<{ promptId: string; value: string }, Ok>;
  'GET /api/interview-sources': Read<Awaited<ReturnType<InterviewSources['status']>>>;
  'PUT /api/interview-sources': Endpoint<InterviewMaterials, Awaited<ReturnType<InterviewSources['status']>>>;
  'GET /api/chats': Read<{ threads: ReturnType<Chat['list']>; activeJob: ActiveJob }>;
  'POST /api/chats': Endpoint<EmptyInput, ChatThread>;
  'GET /api/chats/{id}': Read<ChatThread>;
  'DELETE /api/chats/{id}': Read<{ deleted: boolean }>;
  'POST /api/chats/{id}/messages': Endpoint<ChatInput, TaskStarted>;
  'POST /api/chats/{id}/retry': Endpoint<{ turnId: string }, TaskStarted>;
  'POST /api/problems/{id}/teacher': Endpoint<EmptyInput, ChatThread>;
  'GET /api/teachers/{id}': Read<ChatThread>;
  'POST /api/teachers/{id}/messages': Endpoint<TeacherInput, TaskStarted>;
  'POST /api/problems': Endpoint<Selection, TaskStarted>;
  'GET /api/problems/{id}': Read<State['problems'][number]>;
  'PUT /api/problems/{id}': Endpoint<CodeInput, Saved>;
  'POST /api/problems/{id}/hint': Endpoint<CodeInput, TaskStarted>;
  'POST /api/problems/{id}/review': Endpoint<CodeInput, TaskStarted>;
  'POST /api/language-drills': Endpoint<LanguageSelection, TaskStarted>;
  'GET /api/language-drills/{id}': Read<LanguageDrill>;
  'PUT /api/language-drills/{id}': Endpoint<CodeInput, Saved>;
  'POST /api/language-drills/{id}/reveal': Endpoint<EmptyInput, { revealedAt: string }>;
  'POST /api/interview-jobs': Endpoint<{ title: string; description?: string; urls: string[] }, InterviewJob>;
  'POST /api/interviews': Endpoint<InterviewSelection, TaskStarted>;
  'GET /api/interviews/{id}': Read<ReturnType<typeof publicInterview>>;
  'PUT /api/interviews/{id}': Endpoint<AnswersInput, Saved>;
  'POST /api/interviews/{id}/review': Endpoint<AnswersInput, TaskStarted>;
  'PUT /api/interviews/{id}/voice-settings': Endpoint<Partial<VoiceSettings>, VoiceSettings>;
  'POST /api/interviews/{id}/voice-content': Endpoint<{ language: Locale }, VoiceContent>;
  'GET /api/voice/status': Read<Awaited<ReturnType<CodexVoice['status']>>>;
  'GET /api/voice/options': Read<Awaited<ReturnType<CodexVoice['options']>>>;
  'POST /api/voice/sessions': Endpoint<VoiceStartInput, { id: string; sdp: string; interview?: InterviewProgress }>;
  'DELETE /api/voice/sessions/{id}': Read<{ ended: boolean }>;
  'POST /api/voice/sessions/{id}/action': Endpoint<VoiceActionInput, Awaited<ReturnType<VoiceInterviews['action']>>>;
  'POST /api/voice/sessions/{id}/control': Endpoint<VoiceControlInput, { action: VoiceControlInput['action']; interruptedTurnId: string | null }>;
  'POST /api/voice/sessions/{id}/verify': Endpoint<{ energy: number; received: number }, { verified: boolean }>;
  'POST /api/voice/sessions/{id}/diagnostics': Endpoint<VoiceDiagnosticInput, { logged: boolean }>;
  'POST /api/voice/sessions/{id}/preview': Endpoint<EmptyInput, { started: boolean }>;
  'GET /api/breadth': Read<ReturnType<Study['breadthOverview']>>;
  'GET /api/study/catalog': Read<{ points: KnowledgePoint[] }>;
  'POST /api/study/points': Endpoint<Pick<KnowledgePoint, 'title' | 'category' | 'facets'> & Partial<Pick<KnowledgePoint, 'topic' | 'description' | 'language'>>, KnowledgePoint>;
  'POST /api/study/import': Endpoint<{ kind: string; id: string }, TaskStarted>;
  'POST /api/study/batches': Endpoint<Pick<StudySelection, 'count'> & Partial<Omit<StudySelection, 'count'>>, TaskStarted>;
  'GET /api/study/batches/{id}': Read<ReturnType<typeof publicBatch>>;
  'PUT /api/study/batches/{id}': Endpoint<AnswersInput, Saved>;
  'POST /api/study/batches/{id}/review': Endpoint<AnswersInput, TaskStarted>;
  'POST /api/study/batches/{id}/close': Endpoint<EmptyInput, ReturnType<typeof publicBatch>>;
  'POST /api/study/batches/{id}/items/{itemId}/reveal': Endpoint<EmptyInput, ReturnType<typeof publicBatch>>;
  'GET /api/library': Read<{ items: ReturnType<typeof librarySummary>[] }>;
  'POST /api/library/files': Read<{ item: ReturnType<typeof librarySummary>; duplicate: boolean }>;
  'GET /api/library/{id}': Read<LibraryDetail>;
  'PUT /api/library/{id}': Endpoint<ReturnType<typeof libraryEdit>, ReturnType<typeof librarySummary>>;
  'POST /api/library/urls': Endpoint<{ url: string }, { item: ReturnType<typeof librarySummary>; duplicate: boolean }>;
  'POST /api/library/import-existing': Endpoint<EmptyInput, { imported: number; ids: string[] }>;
  'POST /api/library/organize': Endpoint<{ ids: string[] }, TaskStarted>;
  'POST /api/trainings': Endpoint<{ kind: Exclude<TrainingKind, 'diagnosis'>; interviewId?: string; questionId?: string; debriefId?: string; reviewId?: string; entryId?: string; question?: string; original?: string }, ReturnType<typeof publicTraining>>;
  'POST /api/trainings/diagnosis': Endpoint<{ language: Language; topic: keyof typeof DIAGNOSIS_TOPICS; focus?: string }, TaskStarted>;
  'GET /api/trainings/{id}': Read<ReturnType<typeof publicTraining>>;
  'PUT /api/trainings/{id}': Endpoint<DraftInput, Saved>;
  'POST /api/trainings/{id}/analyze': Endpoint<DraftInput, TaskStarted>;
  'POST /api/trainings/{id}/rewrite': Endpoint<DraftInput, TaskStarted>;
  'POST /api/trainings/{id}/next': Endpoint<{ turnId: string; answer: string }, TaskStarted>;
  'POST /api/trainings/{id}/review': Endpoint<DraftInput, TaskStarted>;
  'POST /api/trainings/{id}/reveal': Endpoint<EmptyInput, ReturnType<typeof publicTraining>>;
  'POST /api/analysis': Endpoint<EmptyInput, TaskStarted>;
  'GET /api/jobs/{id}': Read<JobInfo>;
  'POST /api/jobs/{id}/abort': Endpoint<EmptyInput, Ok>;
}

export type ModelQuestion = Omit<Question, 'id'>;
export interface ModelOutputs {
  problem: ProblemContent;
  hint: Pick<Hint, 'observation' | 'question' | 'checkpoint'>;
  review: ReviewContent;
  analysis: AnalysisContent;
  language: DrillContent;
  interview: Omit<InterviewContent, 'questions'> & { questions: ModelQuestion[] };
  interviewReview: InterviewReviewContent;
  library: ReturnType<typeof libraryMetadata> & { extractedText?: string };
  recognition: { pages: { number: number; text: string }[] };
  notes: { notes: string };
  scenario: Scenario & { title: string };
  followup: Omit<FollowupResult, 'next' | 'stopReason'> & { next: ModelQuestion | null; stopReason?: string };
  compression: CompressionResult;
  diagnosis: DiagnosisResult;
  debrief: DebriefResult;
  quiz: { items: { pointId: string; facet: Facet; title?: string; prompt: string; starterCode?: string; reference: Omit<Reference, 'code'> & { code?: string } }[] };
  quizFeedback: { items: { itemId: string; verdict: Feedback['verdict']; summary: string; gaps: string[] }[] };
  studyImport: { points: (Pick<KnowledgePoint, 'title' | 'category' | 'facets'> & Partial<Pick<KnowledgePoint, 'language' | 'topic' | 'description'>>)[] };
  voiceTranslation: { questions: VoiceContent['questions'] };
}
export interface EventPayloads {
  progress: { message: string };
  done: { result: TaskResult } | { authenticated: boolean };
  aborted: { message: string };
  error: { message: string };
  'chat-start': { chatId: string; turn: ChatTurn };
  message: { chatId: string; turnId: string; text: string };
  auth_url: { url: string };
  device_code: { url: string; code: string };
  prompt: { id: string; message: string };
  prompt_cancelled: { id: string };
  transcript: VoiceTranscript;
  'voice-activity': { activity: 'listening' | 'paused' | 'stopped' | 'failed' | 'thinking' | 'processing' | 'timeout' | 'waiting'; turnId?: string; message?: string };
  'voice-control': VoiceControlInput;
  'voice-error': { message: string };
  'interview-progress': InterviewProgress;
  'interview-notice': { message: string };
  ended: EmptyInput;
}
export interface ContractBundle {
  state: State;
  archive: BackupArchive;
  api: ApiEndpoints;
  models: ModelOutputs;
  events: EventPayloads;
  native: NativeContracts;
}
