import { formatMessage } from './generated/localizations.ts';
import { AppError, LANGUAGES, object, text, type Language } from "./domain.ts";

type TopicSpec = { label: string; concepts: string[]; batch: number };
const topic = (label: string, concepts: string[], batch = 4): TopicSpec => ({ label, concepts, batch });
// Language-specific syllabus, rather than treating every language as Java with different keywords.
export const LANGUAGE_SYLLABUS = {
  dart: {
    foundation: topic(formatMessage('zh', "ui.basicValuesAndCollectionDeclarations"), [formatMessage('zh', "ui.intDoubleBoolStringDeclarationsVarFinalConst.concept1"), formatMessage('zh', "ui.intDoubleBoolStringDeclarationsVarFinalConst.concept2"), formatMessage('zh', "ui.intDoubleBoolStringDeclarationsVarFinalConst.concept3"), formatMessage('zh', "ui.intDoubleBoolStringDeclarationsVarFinalConst.concept4"), formatMessage('zh', "ui.intDoubleBoolStringDeclarationsVarFinalConst.concept5"), formatMessage('zh', "ui.intDoubleBoolStringDeclarationsVarFinalConst.concept6")], 6),
    strings: topic(formatMessage('zh', "ui.stringsAndNumbers"), [formatMessage('zh', "ui.stringInterpolationAndMultilineRawStringsStringSplitting.concept1"), formatMessage('zh', "ui.stringInterpolationAndMultilineRawStringsStringSplitting.concept2"), formatMessage('zh', "ui.stringInterpolationAndMultilineRawStringsStringSplitting.concept3"), formatMessage('zh', "ui.stringInterpolationAndMultilineRawStringsStringSplitting.concept4"), formatMessage('zh', "ui.stringInterpolationAndMultilineRawStringsStringSplitting.concept5"), formatMessage('zh', "ui.stringInterpolationAndMultilineRawStringsStringSplitting.concept6")], 6),
    collections: topic(formatMessage('zh', "ui.collectionOperations"), [formatMessage('zh', "ui.indexAddDeleteSearchMapEntriesPutIfAbsentUpdate.concept1"), formatMessage('zh', "ui.indexAddDeleteSearchMapEntriesPutIfAbsentUpdate.concept2"), formatMessage('zh', "ui.indexAddDeleteSearchMapEntriesPutIfAbsentUpdate.concept3"), formatMessage('zh', "ui.indexAddDeleteSearchMapEntriesPutIfAbsentUpdate.concept4"), formatMessage('zh', "ui.indexAddDeleteSearchMapEntriesPutIfAbsentUpdate.concept5"), formatMessage('zh', "ui.indexAddDeleteSearchMapEntriesPutIfAbsentUpdate.concept6"), formatMessage('zh', "ui.indexAddDeleteSearchMapEntriesPutIfAbsentUpdate.concept7"), formatMessage('zh', "ui.indexAddDeleteSearchMapEntriesPutIfAbsentUpdate.concept8")], 4),
    control: topic(formatMessage('zh', "ui.branchesAndLoops"), [formatMessage('zh', "ui.ifElseAndTernaryConditionalExpressionsClassicFor.concept1"), formatMessage('zh', "ui.ifElseAndTernaryConditionalExpressionsClassicFor.concept2"), formatMessage('zh', "ui.ifElseAndTernaryConditionalExpressionsClassicFor.concept3"), formatMessage('zh', "ui.ifElseAndTernaryConditionalExpressionsClassicFor.concept4"), formatMessage('zh', "ui.ifElseAndTernaryConditionalExpressionsClassicFor.concept5"), formatMessage('zh', "ui.ifElseAndTernaryConditionalExpressionsClassicFor.concept6")], 6),
    functions: topic(formatMessage('zh', "ui.functionsLambdasAndClosures"), [formatMessage('zh', "ui.returnTypesAndArrowFunctionsPositionalOptionalNamed.concept1"), formatMessage('zh', "ui.returnTypesAndArrowFunctionsPositionalOptionalNamed.concept2"), formatMessage('zh', "ui.returnTypesAndArrowFunctionsPositionalOptionalNamed.concept3"), formatMessage('zh', "ui.returnTypesAndArrowFunctionsPositionalOptionalNamed.concept4"), formatMessage('zh', "ui.returnTypesAndArrowFunctionsPositionalOptionalNamed.concept5"), formatMessage('zh', "ui.returnTypesAndArrowFunctionsPositionalOptionalNamed.concept6")], 4),
    objects: topic(formatMessage('zh', "ui.classesAndConstructors"), [formatMessage('zh', "ui.fieldsAndInitializingFormalsWithThisNamedRedirecting.concept1"), formatMessage('zh', "ui.fieldsAndInitializingFormalsWithThisNamedRedirecting.concept2"), formatMessage('zh', "ui.fieldsAndInitializingFormalsWithThisNamedRedirecting.concept3"), formatMessage('zh', "ui.fieldsAndInitializingFormalsWithThisNamedRedirecting.concept4"), formatMessage('zh', "ui.fieldsAndInitializingFormalsWithThisNamedRedirecting.concept5"), formatMessage('zh', "ui.fieldsAndInitializingFormalsWithThisNamedRedirecting.concept6"), formatMessage('zh', "ui.fieldsAndInitializingFormalsWithThisNamedRedirecting.concept7")], 4),
    idioms: topic(formatMessage('zh', "ui.nullSafetyAndSyntaxShortcuts"), [formatMessage('zh', "ui.nullableTypesAndTypePromotionRisksOfAnd.concept1"), formatMessage('zh', "ui.nullableTypesAndTypePromotionRisksOfAnd.concept2"), formatMessage('zh', "ui.nullableTypesAndTypePromotionRisksOfAnd.concept3"), formatMessage('zh', "ui.nullableTypesAndTypePromotionRisksOfAnd.concept4"), formatMessage('zh', "ui.nullableTypesAndTypePromotionRisksOfAnd.concept5"), formatMessage('zh', "ui.nullableTypesAndTypePromotionRisksOfAnd.concept6"), formatMessage('zh', "ui.nullableTypesAndTypePromotionRisksOfAnd.concept7")], 4),
    types: topic(formatMessage('zh', "ui.extensionsMixinsAndTypeModeling"), [formatMessage('zh', "ui.extensionMethodsAndStaticDispatchMixinWithOn.concept1"), formatMessage('zh', "ui.extensionMethodsAndStaticDispatchMixinWithOn.concept2"), formatMessage('zh', "ui.extensionMethodsAndStaticDispatchMixinWithOn.concept3"), formatMessage('zh', "ui.extensionMethodsAndStaticDispatchMixinWithOn.concept4"), formatMessage('zh', "ui.extensionMethodsAndStaticDispatchMixinWithOn.concept5"), formatMessage('zh', "ui.extensionMethodsAndStaticDispatchMixinWithOn.concept6"), formatMessage('zh', "ui.extensionMethodsAndStaticDispatchMixinWithOn.concept7")], 2),
    errors: topic(formatMessage('zh', "ui.exceptionsResourcesAndModules"), [formatMessage('zh', "ui.tryOnCatchFinallyAndRethrowCustomException.concept1"), formatMessage('zh', "ui.tryOnCatchFinallyAndRethrowCustomException.concept2"), formatMessage('zh', "ui.tryOnCatchFinallyAndRethrowCustomException.concept3"), formatMessage('zh', "ui.tryOnCatchFinallyAndRethrowCustomException.concept4"), formatMessage('zh', "ui.tryOnCatchFinallyAndRethrowCustomException.concept5")], 4),
    async: topic(formatMessage('zh', "ui.asyncStreamsAndIsolates"), [formatMessage('zh', "ui.futureAndAsyncAwaitFutureWaitAndExceptions.concept1"), formatMessage('zh', "ui.futureAndAsyncAwaitFutureWaitAndExceptions.concept2"), formatMessage('zh', "ui.futureAndAsyncAwaitFutureWaitAndExceptions.concept3"), formatMessage('zh', "ui.futureAndAsyncAwaitFutureWaitAndExceptions.concept4"), formatMessage('zh', "ui.futureAndAsyncAwaitFutureWaitAndExceptions.concept5"), formatMessage('zh', "ui.futureAndAsyncAwaitFutureWaitAndExceptions.concept6"), formatMessage('zh', "ui.futureAndAsyncAwaitFutureWaitAndExceptions.concept7"), formatMessage('zh', "ui.futureAndAsyncAwaitFutureWaitAndExceptions.concept8")], 2),
    design: topic(formatMessage('zh', "ui.dependencyInjectionAndTestableDesign"), [formatMessage('zh', "ui.constructorInjectionAndInterfaceAbstractionsSimpleImplementationOf.concept1"), formatMessage('zh', "ui.constructorInjectionAndInterfaceAbstractionsSimpleImplementationOf.concept2"), formatMessage('zh', "ui.constructorInjectionAndInterfaceAbstractionsSimpleImplementationOf.concept3"), formatMessage('zh', "ui.constructorInjectionAndInterfaceAbstractionsSimpleImplementationOf.concept4"), formatMessage('zh', "ui.constructorInjectionAndInterfaceAbstractionsSimpleImplementationOf.concept5")], 2),
  },
  kotlin: {
    foundation: topic(formatMessage('zh', "ui.basicValuesAndCollectionDeclarations"), [formatMessage('zh', "ui.intLongDoubleBooleanStringDeclarationsValVar.concept1"), formatMessage('zh', "ui.intLongDoubleBooleanStringDeclarationsValVar.concept2"), formatMessage('zh', "ui.intLongDoubleBooleanStringDeclarationsValVar.concept3"), formatMessage('zh', "ui.intLongDoubleBooleanStringDeclarationsValVar.concept4"), formatMessage('zh', "ui.intLongDoubleBooleanStringDeclarationsValVar.concept5"), formatMessage('zh', "ui.intLongDoubleBooleanStringDeclarationsValVar.concept6")], 6),
    strings: topic(formatMessage('zh', "ui.stringsNumbersAndRanges2"), [formatMessage('zh', "ui.stringTemplatesAndRawStringsTrimIndentTrimMarginNumeric.concept1"), formatMessage('zh', "ui.stringTemplatesAndRawStringsTrimIndentTrimMarginNumeric.concept2"), formatMessage('zh', "ui.stringTemplatesAndRawStringsTrimIndentTrimMarginNumeric.concept3"), formatMessage('zh', "ui.stringTemplatesAndRawStringsTrimIndentTrimMarginNumeric.concept4"), formatMessage('zh', "ui.stringTemplatesAndRawStringsTrimIndentTrimMarginNumeric.concept5"), formatMessage('zh', "ui.stringTemplatesAndRawStringsTrimIndentTrimMarginNumeric.concept6")], 6),
    collections: topic(formatMessage('zh', "ui.collectionsAndSequences"), [formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndImmutabilityBoundaries.concept1"), formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndImmutabilityBoundaries.concept2"), formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndImmutabilityBoundaries.concept3"), formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndImmutabilityBoundaries.concept4"), formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndImmutabilityBoundaries.concept5"), formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndImmutabilityBoundaries.concept6"), formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndImmutabilityBoundaries.concept7"), formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndImmutabilityBoundaries.concept8")], 4),
    control: topic(formatMessage('zh', "ui.branchesAndLoops"), [formatMessage('zh', "ui.ifExpressionsNoTernaryOperatorWhenExpressionsFor.concept1"), formatMessage('zh', "ui.ifExpressionsNoTernaryOperatorWhenExpressionsFor.concept2"), formatMessage('zh', "ui.ifExpressionsNoTernaryOperatorWhenExpressionsFor.concept3"), formatMessage('zh', "ui.ifExpressionsNoTernaryOperatorWhenExpressionsFor.concept4"), formatMessage('zh', "ui.ifExpressionsNoTernaryOperatorWhenExpressionsFor.concept5"), formatMessage('zh', "ui.ifExpressionsNoTernaryOperatorWhenExpressionsFor.concept6"), formatMessage('zh', "ui.ifExpressionsNoTernaryOperatorWhenExpressionsFor.concept7")], 6),
    functions: topic(formatMessage('zh', "ui.functionsLambdasAndHigherOrderFunctions"), [formatMessage('zh', "ui.expressionFunctionsAndReturnTypesNamedDefaultVararg.concept1"), formatMessage('zh', "ui.expressionFunctionsAndReturnTypesNamedDefaultVararg.concept2"), formatMessage('zh', "ui.expressionFunctionsAndReturnTypesNamedDefaultVararg.concept3"), formatMessage('zh', "ui.expressionFunctionsAndReturnTypesNamedDefaultVararg.concept4"), formatMessage('zh', "ui.expressionFunctionsAndReturnTypesNamedDefaultVararg.concept5"), formatMessage('zh', "ui.expressionFunctionsAndReturnTypesNamedDefaultVararg.concept6"), formatMessage('zh', "ui.expressionFunctionsAndReturnTypesNamedDefaultVararg.concept7")], 4),
    objects: topic(formatMessage('zh', "ui.classesConstructorsAndProperties"), [formatMessage('zh', "ui.primarySecondaryConstructorsAndInitDataClassCopy.concept1"), formatMessage('zh', "ui.primarySecondaryConstructorsAndInitDataClassCopy.concept2"), formatMessage('zh', "ui.primarySecondaryConstructorsAndInitDataClassCopy.concept3"), formatMessage('zh', "ui.primarySecondaryConstructorsAndInitDataClassCopy.concept4"), formatMessage('zh', "ui.primarySecondaryConstructorsAndInitDataClassCopy.concept5"), formatMessage('zh', "ui.primarySecondaryConstructorsAndInitDataClassCopy.concept6"), formatMessage('zh', "ui.primarySecondaryConstructorsAndInitDataClassCopy.concept7")], 4),
    idioms: topic(formatMessage('zh', "ui.nullSafetyExtensionsAndSyntaxShortcuts"), [formatMessage('zh', "ui.nullableTypesSafeCallsElvisSmartCastsAnd.concept1"), formatMessage('zh', "ui.nullableTypesSafeCallsElvisSmartCastsAnd.concept2"), formatMessage('zh', "ui.nullableTypesSafeCallsElvisSmartCastsAnd.concept3"), formatMessage('zh', "ui.nullableTypesSafeCallsElvisSmartCastsAnd.concept4"), formatMessage('zh', "ui.nullableTypesSafeCallsElvisSmartCastsAnd.concept5"), formatMessage('zh', "ui.nullableTypesSafeCallsElvisSmartCastsAnd.concept6"), formatMessage('zh', "ui.nullableTypesSafeCallsElvisSmartCastsAnd.concept7")], 4),
    types: topic(formatMessage('zh', "ui.genericsAndTypeModeling"), [formatMessage('zh', "ui.sealedClassInterfaceAndExhaustiveWhenGenericConstraints.concept1"), formatMessage('zh', "ui.sealedClassInterfaceAndExhaustiveWhenGenericConstraints.concept2"), formatMessage('zh', "ui.sealedClassInterfaceAndExhaustiveWhenGenericConstraints.concept3"), formatMessage('zh', "ui.sealedClassInterfaceAndExhaustiveWhenGenericConstraints.concept4"), formatMessage('zh', "ui.sealedClassInterfaceAndExhaustiveWhenGenericConstraints.concept5"), formatMessage('zh', "ui.sealedClassInterfaceAndExhaustiveWhenGenericConstraints.concept6")], 2),
    errors: topic(formatMessage('zh', "ui.exceptionsResourcesAndModules"), [formatMessage('zh', "ui.tryExpressionsThrowFinallyRunCatchingResultUseAnd.concept1"), formatMessage('zh', "ui.tryExpressionsThrowFinallyRunCatchingResultUseAnd.concept2"), formatMessage('zh', "ui.tryExpressionsThrowFinallyRunCatchingResultUseAnd.concept3"), formatMessage('zh', "ui.tryExpressionsThrowFinallyRunCatchingResultUseAnd.concept4"), formatMessage('zh', "ui.tryExpressionsThrowFinallyRunCatchingResultUseAnd.concept5")], 4),
    async: topic(formatMessage('zh', "ui.coroutinesAndConcurrency"), [formatMessage('zh', "ui.suspendFunctionsAndSuspensionCoroutineScopesAndStructured.concept1"), formatMessage('zh', "ui.suspendFunctionsAndSuspensionCoroutineScopesAndStructured.concept2"), formatMessage('zh', "ui.suspendFunctionsAndSuspensionCoroutineScopesAndStructured.concept3"), formatMessage('zh', "ui.suspendFunctionsAndSuspensionCoroutineScopesAndStructured.concept4"), formatMessage('zh', "ui.suspendFunctionsAndSuspensionCoroutineScopesAndStructured.concept5"), formatMessage('zh', "ui.suspendFunctionsAndSuspensionCoroutineScopesAndStructured.concept6"), formatMessage('zh', "ui.suspendFunctionsAndSuspensionCoroutineScopesAndStructured.concept7")], 2),
    design: topic(formatMessage('zh', "ui.dependencyInjectionAndComposition"), [formatMessage('zh', "ui.interfacesAndConstructorInjectionByClassDelegationFake.concept1"), formatMessage('zh', "ui.interfacesAndConstructorInjectionByClassDelegationFake.concept2"), formatMessage('zh', "ui.interfacesAndConstructorInjectionByClassDelegationFake.concept3"), formatMessage('zh', "ui.interfacesAndConstructorInjectionByClassDelegationFake.concept4"), formatMessage('zh', "ui.interfacesAndConstructorInjectionByClassDelegationFake.concept5")], 2),
  },
  swift: {
    foundation: topic(formatMessage('zh', "ui.basicValuesAndCollectionDeclarations"), [formatMessage('zh', "ui.intDoubleBoolStringDeclarationsLetVarAnd.concept1"), formatMessage('zh', "ui.intDoubleBoolStringDeclarationsLetVarAnd.concept2"), formatMessage('zh', "ui.intDoubleBoolStringDeclarationsLetVarAnd.concept3"), formatMessage('zh', "ui.intDoubleBoolStringDeclarationsLetVarAnd.concept4"), formatMessage('zh', "ui.intDoubleBoolStringDeclarationsLetVarAnd.concept5"), formatMessage('zh', "ui.intDoubleBoolStringDeclarationsLetVarAnd.concept6")], 6),
    strings: topic(formatMessage('zh', "ui.stringsNumbersAndRanges"), [formatMessage('zh', "ui.stringInterpolationAndMultilineRawStringsStringIndex.concept1"), formatMessage('zh', "ui.stringInterpolationAndMultilineRawStringsStringIndex.concept2"), formatMessage('zh', "ui.stringInterpolationAndMultilineRawStringsStringIndex.concept3"), formatMessage('zh', "ui.stringInterpolationAndMultilineRawStringsStringIndex.concept4"), formatMessage('zh', "ui.stringInterpolationAndMultilineRawStringsStringIndex.concept5"), formatMessage('zh', "ui.stringInterpolationAndMultilineRawStringsStringIndex.concept6")], 6),
    collections: topic(formatMessage('zh', "ui.collectionOperations"), [formatMessage('zh', "ui.arrayInsertionDeletionAndIndexingDictionaryDefaultValues.concept1"), formatMessage('zh', "ui.arrayInsertionDeletionAndIndexingDictionaryDefaultValues.concept2"), formatMessage('zh', "ui.arrayInsertionDeletionAndIndexingDictionaryDefaultValues.concept3"), formatMessage('zh', "ui.arrayInsertionDeletionAndIndexingDictionaryDefaultValues.concept4"), formatMessage('zh', "ui.arrayInsertionDeletionAndIndexingDictionaryDefaultValues.concept5"), formatMessage('zh', "ui.arrayInsertionDeletionAndIndexingDictionaryDefaultValues.concept6"), formatMessage('zh', "ui.arrayInsertionDeletionAndIndexingDictionaryDefaultValues.concept7"), formatMessage('zh', "ui.arrayInsertionDeletionAndIndexingDictionaryDefaultValues.concept8")], 4),
    control: topic(formatMessage('zh', "ui.branchesAndLoops"), [formatMessage('zh', "ui.ifElseAndTernaryExpressionsSwitchWithPatterns.concept1"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsSwitchWithPatterns.concept2"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsSwitchWithPatterns.concept3"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsSwitchWithPatterns.concept4"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsSwitchWithPatterns.concept5"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsSwitchWithPatterns.concept6"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsSwitchWithPatterns.concept7")], 6),
    functions: topic(formatMessage('zh', "ui.functionsClosuresAndLambdas"), [formatMessage('zh', "ui.argumentLabelsAndOmittedLabelsDefaultParametersVariadic.concept1"), formatMessage('zh', "ui.argumentLabelsAndOmittedLabelsDefaultParametersVariadic.concept2"), formatMessage('zh', "ui.argumentLabelsAndOmittedLabelsDefaultParametersVariadic.concept3"), formatMessage('zh', "ui.argumentLabelsAndOmittedLabelsDefaultParametersVariadic.concept4"), formatMessage('zh', "ui.argumentLabelsAndOmittedLabelsDefaultParametersVariadic.concept5"), formatMessage('zh', "ui.argumentLabelsAndOmittedLabelsDefaultParametersVariadic.concept6"), formatMessage('zh', "ui.argumentLabelsAndOmittedLabelsDefaultParametersVariadic.concept7")], 4),
    objects: topic(formatMessage('zh', "ui.structsClassesAndInitialization"), [formatMessage('zh', "ui.structClassAndValueReferenceSemanticsInitConvenience.concept1"), formatMessage('zh', "ui.structClassAndValueReferenceSemanticsInitConvenience.concept2"), formatMessage('zh', "ui.structClassAndValueReferenceSemanticsInitConvenience.concept3"), formatMessage('zh', "ui.structClassAndValueReferenceSemanticsInitConvenience.concept4"), formatMessage('zh', "ui.structClassAndValueReferenceSemanticsInitConvenience.concept5"), formatMessage('zh', "ui.structClassAndValueReferenceSemanticsInitConvenience.concept6"), formatMessage('zh', "ui.structClassAndValueReferenceSemanticsInitConvenience.concept7"), formatMessage('zh', "ui.structClassAndValueReferenceSemanticsInitConvenience.concept8")], 4),
    idioms: topic(formatMessage('zh', "ui.optionalsExtensionsAndSyntaxShortcuts"), [formatMessage('zh', "ui.ifLetGuardLetOptionalChainingAndExtension.concept1"), formatMessage('zh', "ui.ifLetGuardLetOptionalChainingAndExtension.concept2"), formatMessage('zh', "ui.ifLetGuardLetOptionalChainingAndExtension.concept3"), formatMessage('zh', "ui.ifLetGuardLetOptionalChainingAndExtension.concept4"), formatMessage('zh', "ui.ifLetGuardLetOptionalChainingAndExtension.concept5"), formatMessage('zh', "ui.ifLetGuardLetOptionalChainingAndExtension.concept6"), formatMessage('zh', "ui.ifLetGuardLetOptionalChainingAndExtension.concept7")], 4),
    types: topic(formatMessage('zh', "ui.protocolsEnumsAndGenerics"), [formatMessage('zh', "ui.protocolAndDefaultImplementationsEnumWithAssociatedValues.concept1"), formatMessage('zh', "ui.protocolAndDefaultImplementationsEnumWithAssociatedValues.concept2"), formatMessage('zh', "ui.protocolAndDefaultImplementationsEnumWithAssociatedValues.concept3"), formatMessage('zh', "ui.protocolAndDefaultImplementationsEnumWithAssociatedValues.concept4"), formatMessage('zh', "ui.protocolAndDefaultImplementationsEnumWithAssociatedValues.concept5"), formatMessage('zh', "ui.protocolAndDefaultImplementationsEnumWithAssociatedValues.concept6"), formatMessage('zh', "ui.protocolAndDefaultImplementationsEnumWithAssociatedValues.concept7"), formatMessage('zh', "ui.protocolAndDefaultImplementationsEnumWithAssociatedValues.concept8")], 2),
    errors: topic(formatMessage('zh', "ui.errorsResourcesAndModules"), [formatMessage('zh', "ui.errorThrowsDoCatchTryTryAndRisks.concept1"), formatMessage('zh', "ui.errorThrowsDoCatchTryTryAndRisks.concept2"), formatMessage('zh', "ui.errorThrowsDoCatchTryTryAndRisks.concept3"), formatMessage('zh', "ui.errorThrowsDoCatchTryTryAndRisks.concept4"), formatMessage('zh', "ui.errorThrowsDoCatchTryTryAndRisks.concept5"), formatMessage('zh', "ui.errorThrowsDoCatchTryTryAndRisks.concept6")], 4),
    async: topic(formatMessage('zh', "ui.concurrencyAndIsolation"), [formatMessage('zh', "ui.asyncAwaitTaskAndAsyncLetTaskGroups.concept1"), formatMessage('zh', "ui.asyncAwaitTaskAndAsyncLetTaskGroups.concept2"), formatMessage('zh', "ui.asyncAwaitTaskAndAsyncLetTaskGroups.concept3"), formatMessage('zh', "ui.asyncAwaitTaskAndAsyncLetTaskGroups.concept4"), formatMessage('zh', "ui.asyncAwaitTaskAndAsyncLetTaskGroups.concept5"), formatMessage('zh', "ui.asyncAwaitTaskAndAsyncLetTaskGroups.concept6"), formatMessage('zh', "ui.asyncAwaitTaskAndAsyncLetTaskGroups.concept7"), formatMessage('zh', "ui.asyncAwaitTaskAndAsyncLetTaskGroups.concept8")], 2),
    design: topic(formatMessage('zh', "ui.dependencyInjectionAndComposition"), [formatMessage('zh', "ui.protocolAndInitializerInjectionStructCompositionFakeProtocol.concept1"), formatMessage('zh', "ui.protocolAndInitializerInjectionStructCompositionFakeProtocol.concept2"), formatMessage('zh', "ui.protocolAndInitializerInjectionStructCompositionFakeProtocol.concept3"), formatMessage('zh', "ui.protocolAndInitializerInjectionStructCompositionFakeProtocol.concept4"), formatMessage('zh', "ui.protocolAndInitializerInjectionStructCompositionFakeProtocol.concept5")], 2),
  },
  python: {
    foundation: topic(formatMessage('zh', "ui.basicValuesAndCollectionDeclarations"), [formatMessage('zh', "ui.intFloatBoolStrAssignmentListAndIndexing.concept1"), formatMessage('zh', "ui.intFloatBoolStrAssignmentListAndIndexing.concept2"), formatMessage('zh', "ui.intFloatBoolStrAssignmentListAndIndexing.concept3"), formatMessage('zh', "ui.intFloatBoolStrAssignmentListAndIndexing.concept4"), formatMessage('zh', "ui.intFloatBoolStrAssignmentListAndIndexing.concept5"), formatMessage('zh', "ui.intFloatBoolStrAssignmentListAndIndexing.concept6")], 6),
    strings: topic(formatMessage('zh', "ui.stringsOperatorsAndUnpacking"), [formatMessage('zh', "ui.fStringsAndFormatSpecificationsMultiLineRaw.concept1"), formatMessage('zh', "ui.fStringsAndFormatSpecificationsMultiLineRaw.concept2"), formatMessage('zh', "ui.fStringsAndFormatSpecificationsMultiLineRaw.concept3"), formatMessage('zh', "ui.fStringsAndFormatSpecificationsMultiLineRaw.concept4"), formatMessage('zh', "ui.fStringsAndFormatSpecificationsMultiLineRaw.concept5"), formatMessage('zh', "ui.fStringsAndFormatSpecificationsMultiLineRaw.concept6"), formatMessage('zh', "ui.fStringsAndFormatSpecificationsMultiLineRaw.concept7")], 6),
    collections: topic(formatMessage('zh', "ui.collectionsAndIterators"), [formatMessage('zh', "ui.listAddDeleteSearchAndShallowCopyDict.concept1"), formatMessage('zh', "ui.listAddDeleteSearchAndShallowCopyDict.concept2"), formatMessage('zh', "ui.listAddDeleteSearchAndShallowCopyDict.concept3"), formatMessage('zh', "ui.listAddDeleteSearchAndShallowCopyDict.concept4"), formatMessage('zh', "ui.listAddDeleteSearchAndShallowCopyDict.concept5"), formatMessage('zh', "ui.listAddDeleteSearchAndShallowCopyDict.concept6"), formatMessage('zh', "ui.listAddDeleteSearchAndShallowCopyDict.concept7"), formatMessage('zh', "ui.listAddDeleteSearchAndShallowCopyDict.concept8")], 4),
    control: topic(formatMessage('zh', "ui.branchesAndLoops"), [formatMessage('zh', "ui.ifElifElseConditionalExpressionXIfCond.concept1"), formatMessage('zh', "ui.ifElifElseConditionalExpressionXIfCond.concept2"), formatMessage('zh', "ui.ifElifElseConditionalExpressionXIfCond.concept3"), formatMessage('zh', "ui.ifElifElseConditionalExpressionXIfCond.concept4"), formatMessage('zh', "ui.ifElifElseConditionalExpressionXIfCond.concept5"), formatMessage('zh', "ui.ifElifElseConditionalExpressionXIfCond.concept6"), formatMessage('zh', "ui.ifElifElseConditionalExpressionXIfCond.concept7")], 6),
    functions: topic(formatMessage('zh', "ui.functionsLambdasAndClosures"), [formatMessage('zh', "ui.positionalKeywordDefaultParametersPositionalOnlyKeywordOnly.concept1"), formatMessage('zh', "ui.positionalKeywordDefaultParametersPositionalOnlyKeywordOnly.concept2"), formatMessage('zh', "ui.positionalKeywordDefaultParametersPositionalOnlyKeywordOnly.concept3"), formatMessage('zh', "ui.positionalKeywordDefaultParametersPositionalOnlyKeywordOnly.concept4"), formatMessage('zh', "ui.positionalKeywordDefaultParametersPositionalOnlyKeywordOnly.concept5"), formatMessage('zh', "ui.positionalKeywordDefaultParametersPositionalOnlyKeywordOnly.concept6"), formatMessage('zh', "ui.positionalKeywordDefaultParametersPositionalOnlyKeywordOnly.concept7"), formatMessage('zh', "ui.positionalKeywordDefaultParametersPositionalOnlyKeywordOnly.concept8")], 4),
    objects: topic(formatMessage('zh', "ui.classesInitializationAndDataClasses"), [formatMessage('zh', "ui.classSelfInitTheDifferenceBetweenNewAnd.concept1"), formatMessage('zh', "ui.classSelfInitTheDifferenceBetweenNewAnd.concept2"), formatMessage('zh', "ui.classSelfInitTheDifferenceBetweenNewAnd.concept3"), formatMessage('zh', "ui.classSelfInitTheDifferenceBetweenNewAnd.concept4"), formatMessage('zh', "ui.classSelfInitTheDifferenceBetweenNewAnd.concept5"), formatMessage('zh', "ui.classSelfInitTheDifferenceBetweenNewAnd.concept6"), formatMessage('zh', "ui.classSelfInitTheDifferenceBetweenNewAnd.concept7")], 4),
    idioms: topic(formatMessage('zh', "ui.decoratorsAndSyntaxShortcuts"), [formatMessage('zh', "ui.functionDecoratorsAndWrapsDecoratorsWithParametersGenerators.concept1"), formatMessage('zh', "ui.functionDecoratorsAndWrapsDecoratorsWithParametersGenerators.concept2"), formatMessage('zh', "ui.functionDecoratorsAndWrapsDecoratorsWithParametersGenerators.concept3"), formatMessage('zh', "ui.functionDecoratorsAndWrapsDecoratorsWithParametersGenerators.concept4"), formatMessage('zh', "ui.functionDecoratorsAndWrapsDecoratorsWithParametersGenerators.concept5"), formatMessage('zh', "ui.functionDecoratorsAndWrapsDecoratorsWithParametersGenerators.concept6"), formatMessage('zh', "ui.functionDecoratorsAndWrapsDecoratorsWithParametersGenerators.concept7")], 4),
    types: topic(formatMessage('zh', "ui.typesAndProtocolModeling"), [formatMessage('zh', "ui.genericTypeAnnotationsAndTypeVarProtocolAndStructural.concept1"), formatMessage('zh', "ui.genericTypeAnnotationsAndTypeVarProtocolAndStructural.concept2"), formatMessage('zh', "ui.genericTypeAnnotationsAndTypeVarProtocolAndStructural.concept3"), formatMessage('zh', "ui.genericTypeAnnotationsAndTypeVarProtocolAndStructural.concept4"), formatMessage('zh', "ui.genericTypeAnnotationsAndTypeVarProtocolAndStructural.concept5"), formatMessage('zh', "ui.genericTypeAnnotationsAndTypeVarProtocolAndStructural.concept6")], 2),
    errors: topic(formatMessage('zh', "ui.exceptionsResourcesAndModules"), [formatMessage('zh', "ui.tryExceptElseFinallyRaiseAndExceptionChaining.concept1"), formatMessage('zh', "ui.tryExceptElseFinallyRaiseAndExceptionChaining.concept2"), formatMessage('zh', "ui.tryExceptElseFinallyRaiseAndExceptionChaining.concept3"), formatMessage('zh', "ui.tryExceptElseFinallyRaiseAndExceptionChaining.concept4"), formatMessage('zh', "ui.tryExceptElseFinallyRaiseAndExceptionChaining.concept5"), formatMessage('zh', "ui.tryExceptElseFinallyRaiseAndExceptionChaining.concept6")], 4),
    async: topic(formatMessage('zh', "ui.asyncAndConcurrency"), [formatMessage('zh', "ui.asyncAwaitAndAsyncioRunCreateTaskGather.concept1"), formatMessage('zh', "ui.asyncAwaitAndAsyncioRunCreateTaskGather.concept2"), formatMessage('zh', "ui.asyncAwaitAndAsyncioRunCreateTaskGather.concept3"), formatMessage('zh', "ui.asyncAwaitAndAsyncioRunCreateTaskGather.concept4"), formatMessage('zh', "ui.asyncAwaitAndAsyncioRunCreateTaskGather.concept5"), formatMessage('zh', "ui.asyncAwaitAndAsyncioRunCreateTaskGather.concept6"), formatMessage('zh', "ui.asyncAwaitAndAsyncioRunCreateTaskGather.concept7")], 2),
    design: topic(formatMessage('zh', "ui.dependencyInjectionAndComposition"), [formatMessage('zh', "ui.constructorInjectionAndProtocolCallableObjectFunctionInjection.concept1"), formatMessage('zh', "ui.constructorInjectionAndProtocolCallableObjectFunctionInjection.concept2"), formatMessage('zh', "ui.constructorInjectionAndProtocolCallableObjectFunctionInjection.concept3"), formatMessage('zh', "ui.constructorInjectionAndProtocolCallableObjectFunctionInjection.concept4"), formatMessage('zh', "ui.constructorInjectionAndProtocolCallableObjectFunctionInjection.concept5")], 2),
  },
  go: {
    foundation: topic(formatMessage('zh', "ui.basicValuesAndCollectionDeclarations"), [formatMessage('zh', "ui.intFloat64BoolStringDeclarationsVarAndConst.concept1"), formatMessage('zh', "ui.intFloat64BoolStringDeclarationsVarAndConst.concept2"), formatMessage('zh', "ui.intFloat64BoolStringDeclarationsVarAndConst.concept3"), formatMessage('zh', "ui.intFloat64BoolStringDeclarationsVarAndConst.concept4"), formatMessage('zh', "ui.intFloat64BoolStringDeclarationsVarAndConst.concept5"), formatMessage('zh', "ui.intFloat64BoolStringDeclarationsVarAndConst.concept6"), formatMessage('zh', "ui.intFloat64BoolStringDeclarationsVarAndConst.concept7")], 6),
    strings: topic(formatMessage('zh', "ui.stringsNumbersAndPointers"), [formatMessage('zh', "ui.stringRuneByteAndUTFRawStringsStrconv.concept1"), formatMessage('zh', "ui.stringRuneByteAndUTFRawStringsStrconv.concept2"), formatMessage('zh', "ui.stringRuneByteAndUTFRawStringsStrconv.concept3"), formatMessage('zh', "ui.stringRuneByteAndUTFRawStringsStrconv.concept4"), formatMessage('zh', "ui.stringRuneByteAndUTFRawStringsStrconv.concept5"), formatMessage('zh', "ui.stringRuneByteAndUTFRawStringsStrconv.concept6")], 6),
    collections: topic(formatMessage('zh', "ui.arraysSlicesAndMaps"), [formatMessage('zh', "ui.lenCapAppendCopySliceExpressionsAndUnderlying.concept1"), formatMessage('zh', "ui.lenCapAppendCopySliceExpressionsAndUnderlying.concept2"), formatMessage('zh', "ui.lenCapAppendCopySliceExpressionsAndUnderlying.concept3"), formatMessage('zh', "ui.lenCapAppendCopySliceExpressionsAndUnderlying.concept4"), formatMessage('zh', "ui.lenCapAppendCopySliceExpressionsAndUnderlying.concept5"), formatMessage('zh', "ui.lenCapAppendCopySliceExpressionsAndUnderlying.concept6"), formatMessage('zh', "ui.lenCapAppendCopySliceExpressionsAndUnderlying.concept7"), formatMessage('zh', "ui.lenCapAppendCopySliceExpressionsAndUnderlying.concept8")], 4),
    control: topic(formatMessage('zh', "ui.branchesAndLoops"), [formatMessage('zh', "ui.ifWithInitializationStatementsNoTernaryOperatorThree.concept1"), formatMessage('zh', "ui.ifWithInitializationStatementsNoTernaryOperatorThree.concept2"), formatMessage('zh', "ui.ifWithInitializationStatementsNoTernaryOperatorThree.concept3"), formatMessage('zh', "ui.ifWithInitializationStatementsNoTernaryOperatorThree.concept4"), formatMessage('zh', "ui.ifWithInitializationStatementsNoTernaryOperatorThree.concept5"), formatMessage('zh', "ui.ifWithInitializationStatementsNoTernaryOperatorThree.concept6"), formatMessage('zh', "ui.ifWithInitializationStatementsNoTernaryOperatorThree.concept7")], 6),
    functions: topic(formatMessage('zh', "ui.functionsAnonymousFunctionsAndClosures"), [formatMessage('zh', "ui.multipleReturnValuesAndNamedReturnValuesVariadic.concept1"), formatMessage('zh', "ui.multipleReturnValuesAndNamedReturnValuesVariadic.concept2"), formatMessage('zh', "ui.multipleReturnValuesAndNamedReturnValuesVariadic.concept3"), formatMessage('zh', "ui.multipleReturnValuesAndNamedReturnValuesVariadic.concept4"), formatMessage('zh', "ui.multipleReturnValuesAndNamedReturnValuesVariadic.concept5"), formatMessage('zh', "ui.multipleReturnValuesAndNamedReturnValuesVariadic.concept6")], 4),
    objects: topic(formatMessage('zh', "ui.structsMethodsAndInterfaces"), [formatMessage('zh', "ui.structAndCompositeLiteralsNewXFactoryConventionNo.concept1"), formatMessage('zh', "ui.structAndCompositeLiteralsNewXFactoryConventionNo.concept2"), formatMessage('zh', "ui.structAndCompositeLiteralsNewXFactoryConventionNo.concept3"), formatMessage('zh', "ui.structAndCompositeLiteralsNewXFactoryConventionNo.concept4"), formatMessage('zh', "ui.structAndCompositeLiteralsNewXFactoryConventionNo.concept5"), formatMessage('zh', "ui.structAndCompositeLiteralsNewXFactoryConventionNo.concept6"), formatMessage('zh', "ui.structAndCompositeLiteralsNewXFactoryConventionNo.concept7")], 4),
    idioms: topic(formatMessage('zh', "ui.commonIdioms"), [formatMessage('zh', "ui.commaOkAndTypeAssertionsBlankIdentifierIota.concept1"), formatMessage('zh', "ui.commaOkAndTypeAssertionsBlankIdentifierIota.concept2"), formatMessage('zh', "ui.commaOkAndTypeAssertionsBlankIdentifierIota.concept3"), formatMessage('zh', "ui.commaOkAndTypeAssertionsBlankIdentifierIota.concept4"), formatMessage('zh', "ui.commaOkAndTypeAssertionsBlankIdentifierIota.concept5"), formatMessage('zh', "ui.commaOkAndTypeAssertionsBlankIdentifierIota.concept6"), formatMessage('zh', "ui.commaOkAndTypeAssertionsBlankIdentifierIota.concept7")], 4),
    types: topic(formatMessage('zh', "ui.genericsAndTypeModeling"), [formatMessage('zh', "ui.typeParametersAndConstraintsTypeSetsAndGeneric.concept1"), formatMessage('zh', "ui.typeParametersAndConstraintsTypeSetsAndGeneric.concept2"), formatMessage('zh', "ui.typeParametersAndConstraintsTypeSetsAndGeneric.concept3"), formatMessage('zh', "ui.typeParametersAndConstraintsTypeSetsAndGeneric.concept4"), formatMessage('zh', "ui.typeParametersAndConstraintsTypeSetsAndGeneric.concept5"), formatMessage('zh', "ui.typeParametersAndConstraintsTypeSetsAndGeneric.concept6")], 2),
    errors: topic(formatMessage('zh', "ui.errorsResourcesAndModules"), [formatMessage('zh', "ui.errorReturnsAndEarlyExitsErrorsIsAs.concept1"), formatMessage('zh', "ui.errorReturnsAndEarlyExitsErrorsIsAs.concept2"), formatMessage('zh', "ui.errorReturnsAndEarlyExitsErrorsIsAs.concept3"), formatMessage('zh', "ui.errorReturnsAndEarlyExitsErrorsIsAs.concept4"), formatMessage('zh', "ui.errorReturnsAndEarlyExitsErrorsIsAs.concept5"), formatMessage('zh', "ui.errorReturnsAndEarlyExitsErrorsIsAs.concept6")], 4),
    async: topic(formatMessage('zh', "ui.goroutinesAndChannels"), [formatMessage('zh', "ui.goStartupAndSynchronizedWaitingBufferedUnbufferedChan.concept1"), formatMessage('zh', "ui.goStartupAndSynchronizedWaitingBufferedUnbufferedChan.concept2"), formatMessage('zh', "ui.goStartupAndSynchronizedWaitingBufferedUnbufferedChan.concept3"), formatMessage('zh', "ui.goStartupAndSynchronizedWaitingBufferedUnbufferedChan.concept4"), formatMessage('zh', "ui.goStartupAndSynchronizedWaitingBufferedUnbufferedChan.concept5"), formatMessage('zh', "ui.goStartupAndSynchronizedWaitingBufferedUnbufferedChan.concept6"), formatMessage('zh', "ui.goStartupAndSynchronizedWaitingBufferedUnbufferedChan.concept7"), formatMessage('zh', "ui.goStartupAndSynchronizedWaitingBufferedUnbufferedChan.concept8")], 2),
    design: topic(formatMessage('zh', "ui.dependencyInjectionAndComposition"), [formatMessage('zh', "ui.smallInterfacesAndFactoryFunctionInjectionStructField.concept1"), formatMessage('zh', "ui.smallInterfacesAndFactoryFunctionInjectionStructField.concept2"), formatMessage('zh', "ui.smallInterfacesAndFactoryFunctionInjectionStructField.concept3"), formatMessage('zh', "ui.smallInterfacesAndFactoryFunctionInjectionStructField.concept4"), formatMessage('zh', "ui.smallInterfacesAndFactoryFunctionInjectionStructField.concept5")], 2),
  },
  java: {
    foundation: topic(formatMessage('zh', "ui.basicValuesAndCollectionDeclarations"), [formatMessage('zh', "ui.intLongDoubleBooleanStringDeclarationsVarFinal.concept1"), formatMessage('zh', "ui.intLongDoubleBooleanStringDeclarationsVarFinal.concept2"), formatMessage('zh', "ui.intLongDoubleBooleanStringDeclarationsVarFinal.concept3"), formatMessage('zh', "ui.intLongDoubleBooleanStringDeclarationsVarFinal.concept4"), formatMessage('zh', "ui.intLongDoubleBooleanStringDeclarationsVarFinal.concept5"), formatMessage('zh', "ui.intLongDoubleBooleanStringDeclarationsVarFinal.concept6"), formatMessage('zh', "ui.intLongDoubleBooleanStringDeclarationsVarFinal.concept7")], 6),
    strings: topic(formatMessage('zh', "ui.stringsAndOperators"), [formatMessage('zh', "ui.stringConcatenationStringBuilderTextBlocksNumericParsingAnd.concept1"), formatMessage('zh', "ui.stringConcatenationStringBuilderTextBlocksNumericParsingAnd.concept2"), formatMessage('zh', "ui.stringConcatenationStringBuilderTextBlocksNumericParsingAnd.concept3"), formatMessage('zh', "ui.stringConcatenationStringBuilderTextBlocksNumericParsingAnd.concept4"), formatMessage('zh', "ui.stringConcatenationStringBuilderTextBlocksNumericParsingAnd.concept5"), formatMessage('zh', "ui.stringConcatenationStringBuilderTextBlocksNumericParsingAnd.concept6"), formatMessage('zh', "ui.stringConcatenationStringBuilderTextBlocksNumericParsingAnd.concept7")], 6),
    collections: topic(formatMessage('zh', "ui.collectionsAndStreams"), [formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndListOf.concept1"), formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndListOf.concept2"), formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndListOf.concept3"), formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndListOf.concept4"), formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndListOf.concept5"), formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndListOf.concept6"), formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndListOf.concept7"), formatMessage('zh', "ui.collectionAddDeleteSearchOperationsAndListOf.concept8")], 4),
    control: topic(formatMessage('zh', "ui.branchesAndLoops"), [formatMessage('zh', "ui.ifElseAndTernaryExpressionsTraditionalForEnhanced.concept1"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsTraditionalForEnhanced.concept2"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsTraditionalForEnhanced.concept3"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsTraditionalForEnhanced.concept4"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsTraditionalForEnhanced.concept5"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsTraditionalForEnhanced.concept6"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsTraditionalForEnhanced.concept7"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsTraditionalForEnhanced.concept8")], 6),
    functions: topic(formatMessage('zh', "ui.methodsLambdasAndFunctionalInterfaces"), [formatMessage('zh', "ui.methodDefinitionsOverloadingVarargsFunctionalInterfacesAndFunctionalInterface.concept1"), formatMessage('zh', "ui.methodDefinitionsOverloadingVarargsFunctionalInterfacesAndFunctionalInterface.concept2"), formatMessage('zh', "ui.methodDefinitionsOverloadingVarargsFunctionalInterfacesAndFunctionalInterface.concept3"), formatMessage('zh', "ui.methodDefinitionsOverloadingVarargsFunctionalInterfacesAndFunctionalInterface.concept4"), formatMessage('zh', "ui.methodDefinitionsOverloadingVarargsFunctionalInterfacesAndFunctionalInterface.concept5"), formatMessage('zh', "ui.methodDefinitionsOverloadingVarargsFunctionalInterfacesAndFunctionalInterface.concept6")], 4),
    objects: topic(formatMessage('zh', "ui.classesAndConstructors"), [formatMessage('zh', "ui.fieldsConstructorsThisSuperAccessControlAndStatic.concept1"), formatMessage('zh', "ui.fieldsConstructorsThisSuperAccessControlAndStatic.concept2"), formatMessage('zh', "ui.fieldsConstructorsThisSuperAccessControlAndStatic.concept3"), formatMessage('zh', "ui.fieldsConstructorsThisSuperAccessControlAndStatic.concept4"), formatMessage('zh', "ui.fieldsConstructorsThisSuperAccessControlAndStatic.concept5"), formatMessage('zh', "ui.fieldsConstructorsThisSuperAccessControlAndStatic.concept6"), formatMessage('zh', "ui.fieldsConstructorsThisSuperAccessControlAndStatic.concept7"), formatMessage('zh', "ui.fieldsConstructorsThisSuperAccessControlAndStatic.concept8")], 4),
    idioms: topic(formatMessage('zh', "ui.commonPatternsAndSyntaxShortcuts"), [formatMessage('zh', "ui.optionalAndAvoidingMisusePatternInstanceofTryWith.concept1"), formatMessage('zh', "ui.optionalAndAvoidingMisusePatternInstanceofTryWith.concept2"), formatMessage('zh', "ui.optionalAndAvoidingMisusePatternInstanceofTryWith.concept3"), formatMessage('zh', "ui.optionalAndAvoidingMisusePatternInstanceofTryWith.concept4"), formatMessage('zh', "ui.optionalAndAvoidingMisusePatternInstanceofTryWith.concept5"), formatMessage('zh', "ui.optionalAndAvoidingMisusePatternInstanceofTryWith.concept6")], 4),
    types: topic(formatMessage('zh', "ui.genericsAndTypeModeling"), [formatMessage('zh', "ui.genericClassesMethodsExtendsSuperWildcardsAndPECS.concept1"), formatMessage('zh', "ui.genericClassesMethodsExtendsSuperWildcardsAndPECS.concept2"), formatMessage('zh', "ui.genericClassesMethodsExtendsSuperWildcardsAndPECS.concept3"), formatMessage('zh', "ui.genericClassesMethodsExtendsSuperWildcardsAndPECS.concept4"), formatMessage('zh', "ui.genericClassesMethodsExtendsSuperWildcardsAndPECS.concept5"), formatMessage('zh', "ui.genericClassesMethodsExtendsSuperWildcardsAndPECS.concept6")], 2),
    errors: topic(formatMessage('zh', "ui.exceptionsResourcesAndModules"), [formatMessage('zh', "ui.checkedUncheckedExceptionsTryCatchFinallyThrowThrows.concept1"), formatMessage('zh', "ui.checkedUncheckedExceptionsTryCatchFinallyThrowThrows.concept2"), formatMessage('zh', "ui.checkedUncheckedExceptionsTryCatchFinallyThrowThrows.concept3"), formatMessage('zh', "ui.checkedUncheckedExceptionsTryCatchFinallyThrowThrows.concept4"), formatMessage('zh', "ui.checkedUncheckedExceptionsTryCatchFinallyThrowThrows.concept5"), formatMessage('zh', "ui.checkedUncheckedExceptionsTryCatchFinallyThrowThrows.concept6")], 4),
    async: topic(formatMessage('zh', "ui.concurrencyAndAsync"), [formatMessage('zh', "ui.threadRunnableExecutorServiceFutureCompletableFutureSynchronizedVolatileAtomic.concept1"), formatMessage('zh', "ui.threadRunnableExecutorServiceFutureCompletableFutureSynchronizedVolatileAtomic.concept2"), formatMessage('zh', "ui.threadRunnableExecutorServiceFutureCompletableFutureSynchronizedVolatileAtomic.concept3"), formatMessage('zh', "ui.threadRunnableExecutorServiceFutureCompletableFutureSynchronizedVolatileAtomic.concept4"), formatMessage('zh', "ui.threadRunnableExecutorServiceFutureCompletableFutureSynchronizedVolatileAtomic.concept5"), formatMessage('zh', "ui.threadRunnableExecutorServiceFutureCompletableFutureSynchronizedVolatileAtomic.concept6"), formatMessage('zh', "ui.threadRunnableExecutorServiceFutureCompletableFutureSynchronizedVolatileAtomic.concept7")], 2),
    design: topic(formatMessage('zh', "ui.dependencyInjectionAndComposition"), [formatMessage('zh', "ui.interfacesAndConstructorInjectionFakeImplementationsAndTestability.concept1"), formatMessage('zh', "ui.interfacesAndConstructorInjectionFakeImplementationsAndTestability.concept2"), formatMessage('zh', "ui.interfacesAndConstructorInjectionFakeImplementationsAndTestability.concept3"), formatMessage('zh', "ui.interfacesAndConstructorInjectionFakeImplementationsAndTestability.concept4"), formatMessage('zh', "ui.interfacesAndConstructorInjectionFakeImplementationsAndTestability.concept5")], 2),
  },
  javascript: {
    foundation: topic(formatMessage('zh', "ui.basicValuesAndCollectionDeclarations"), [formatMessage('zh', "ui.numberBooleanStringDeclarationsLetConstAndScope.concept1"), formatMessage('zh', "ui.numberBooleanStringDeclarationsLetConstAndScope.concept2"), formatMessage('zh', "ui.numberBooleanStringDeclarationsLetConstAndScope.concept3"), formatMessage('zh', "ui.numberBooleanStringDeclarationsLetConstAndScope.concept4"), formatMessage('zh', "ui.numberBooleanStringDeclarationsLetConstAndScope.concept5"), formatMessage('zh', "ui.numberBooleanStringDeclarationsLetConstAndScope.concept6"), formatMessage('zh', "ui.numberBooleanStringDeclarationsLetConstAndScope.concept7")], 6),
    strings: topic(formatMessage('zh', "ui.stringsAndOperators"), [formatMessage('zh', "ui.templateStringsStringSplittingConcatenationNumericConversionAnd.concept1"), formatMessage('zh', "ui.templateStringsStringSplittingConcatenationNumericConversionAnd.concept2"), formatMessage('zh', "ui.templateStringsStringSplittingConcatenationNumericConversionAnd.concept3"), formatMessage('zh', "ui.templateStringsStringSplittingConcatenationNumericConversionAnd.concept4"), formatMessage('zh', "ui.templateStringsStringSplittingConcatenationNumericConversionAnd.concept5"), formatMessage('zh', "ui.templateStringsStringSplittingConcatenationNumericConversionAnd.concept6")], 6),
    collections: topic(formatMessage('zh', "ui.collectionOperations"), [formatMessage('zh', "ui.arrayCreateReadUpdateDeleteMapFilterFlatMap.concept1"), formatMessage('zh', "ui.arrayCreateReadUpdateDeleteMapFilterFlatMap.concept2"), formatMessage('zh', "ui.arrayCreateReadUpdateDeleteMapFilterFlatMap.concept3"), formatMessage('zh', "ui.arrayCreateReadUpdateDeleteMapFilterFlatMap.concept4"), formatMessage('zh', "ui.arrayCreateReadUpdateDeleteMapFilterFlatMap.concept5"), formatMessage('zh', "ui.arrayCreateReadUpdateDeleteMapFilterFlatMap.concept6"), formatMessage('zh', "ui.arrayCreateReadUpdateDeleteMapFilterFlatMap.concept7")], 4),
    control: topic(formatMessage('zh', "ui.branchesAndLoops"), [formatMessage('zh', "ui.ifElseAndTernaryExpressionsClassicForDifferences.concept1"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsClassicForDifferences.concept2"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsClassicForDifferences.concept3"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsClassicForDifferences.concept4"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsClassicForDifferences.concept5"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsClassicForDifferences.concept6")], 6),
    functions: topic(formatMessage('zh', "ui.functionsLambdasAndClosures"), [formatMessage('zh', "ui.functionAndArrowFunctionsDefaultRestParametersHigher.concept1"), formatMessage('zh', "ui.functionAndArrowFunctionsDefaultRestParametersHigher.concept2"), formatMessage('zh', "ui.functionAndArrowFunctionsDefaultRestParametersHigher.concept3"), formatMessage('zh', "ui.functionAndArrowFunctionsDefaultRestParametersHigher.concept4"), formatMessage('zh', "ui.functionAndArrowFunctionsDefaultRestParametersHigher.concept5"), formatMessage('zh', "ui.functionAndArrowFunctionsDefaultRestParametersHigher.concept6")], 4),
    objects: topic(formatMessage('zh', "ui.classesAndPrototypes"), [formatMessage('zh', "ui.classConstructorExtendsSuperGetterSetterStaticPrivate.concept1"), formatMessage('zh', "ui.classConstructorExtendsSuperGetterSetterStaticPrivate.concept2"), formatMessage('zh', "ui.classConstructorExtendsSuperGetterSetterStaticPrivate.concept3"), formatMessage('zh', "ui.classConstructorExtendsSuperGetterSetterStaticPrivate.concept4"), formatMessage('zh', "ui.classConstructorExtendsSuperGetterSetterStaticPrivate.concept5"), formatMessage('zh', "ui.classConstructorExtendsSuperGetterSetterStaticPrivate.concept6")], 4),
    idioms: topic(formatMessage('zh', "ui.syntaxShortcutsAndIdioms"), [formatMessage('zh', "ui.destructuringAndDefaultValuesSpreadSyntaxAndLogical.concept1"), formatMessage('zh', "ui.destructuringAndDefaultValuesSpreadSyntaxAndLogical.concept2"), formatMessage('zh', "ui.destructuringAndDefaultValuesSpreadSyntaxAndLogical.concept3"), formatMessage('zh', "ui.destructuringAndDefaultValuesSpreadSyntaxAndLogical.concept4"), formatMessage('zh', "ui.destructuringAndDefaultValuesSpreadSyntaxAndLogical.concept5"), formatMessage('zh', "ui.destructuringAndDefaultValuesSpreadSyntaxAndLogical.concept6")], 4),
    types: topic(formatMessage('zh', "ui.objectProtocolsAndTypeChecks"), [formatMessage('zh', "ui.typeofInstanceofSymbolAndTheIterationProtocolProperty.concept1"), formatMessage('zh', "ui.typeofInstanceofSymbolAndTheIterationProtocolProperty.concept2"), formatMessage('zh', "ui.typeofInstanceofSymbolAndTheIterationProtocolProperty.concept3"), formatMessage('zh', "ui.typeofInstanceofSymbolAndTheIterationProtocolProperty.concept4"), formatMessage('zh', "ui.typeofInstanceofSymbolAndTheIterationProtocolProperty.concept5")], 2),
    errors: topic(formatMessage('zh', "ui.exceptionsAndModules"), [formatMessage('zh', "ui.tryCatchFinallyThrowCustomErrorESImport.concept1"), formatMessage('zh', "ui.tryCatchFinallyThrowCustomErrorESImport.concept2"), formatMessage('zh', "ui.tryCatchFinallyThrowCustomErrorESImport.concept3"), formatMessage('zh', "ui.tryCatchFinallyThrowCustomErrorESImport.concept4"), formatMessage('zh', "ui.tryCatchFinallyThrowCustomErrorESImport.concept5")], 4),
    async: topic(formatMessage('zh', "ui.async"), [formatMessage('zh', "ui.promiseAsyncAwaitPromiseAllAllSettledErrorsAnd.concept1"), formatMessage('zh', "ui.promiseAsyncAwaitPromiseAllAllSettledErrorsAnd.concept2"), formatMessage('zh', "ui.promiseAsyncAwaitPromiseAllAllSettledErrorsAnd.concept3"), formatMessage('zh', "ui.promiseAsyncAwaitPromiseAllAllSettledErrorsAnd.concept4"), formatMessage('zh', "ui.promiseAsyncAwaitPromiseAllAllSettledErrorsAnd.concept5"), formatMessage('zh', "ui.promiseAsyncAwaitPromiseAllAllSettledErrorsAnd.concept6")], 2),
    design: topic(formatMessage('zh', "ui.dependencyInjectionAndComposition"), [formatMessage('zh', "ui.constructorInjectionFunctionInjectionFakeImplementationsFactoriesAnd.concept1"), formatMessage('zh', "ui.constructorInjectionFunctionInjectionFakeImplementationsFactoriesAnd.concept2"), formatMessage('zh', "ui.constructorInjectionFunctionInjectionFakeImplementationsFactoriesAnd.concept3"), formatMessage('zh', "ui.constructorInjectionFunctionInjectionFakeImplementationsFactoriesAnd.concept4"), formatMessage('zh', "ui.constructorInjectionFunctionInjectionFakeImplementationsFactoriesAnd.concept5")], 2),
  },
  typescript: {
    foundation: topic(formatMessage('zh', "ui.basicTypesAndCollectionDeclarations"), [formatMessage('zh', "ui.numberBooleanStringAnnotationsLetConstAndType.concept1"), formatMessage('zh', "ui.numberBooleanStringAnnotationsLetConstAndType.concept2"), formatMessage('zh', "ui.numberBooleanStringAnnotationsLetConstAndType.concept3"), formatMessage('zh', "ui.numberBooleanStringAnnotationsLetConstAndType.concept4"), formatMessage('zh', "ui.numberBooleanStringAnnotationsLetConstAndType.concept5"), formatMessage('zh', "ui.numberBooleanStringAnnotationsLetConstAndType.concept6"), formatMessage('zh', "ui.numberBooleanStringAnnotationsLetConstAndType.concept7")], 6),
    strings: topic(formatMessage('zh', "ui.stringsOperatorsAndTuples"), [formatMessage('zh', "ui.templateStringsStringNumberConversionStrictEqualityTruthiness.concept1"), formatMessage('zh', "ui.templateStringsStringNumberConversionStrictEqualityTruthiness.concept2"), formatMessage('zh', "ui.templateStringsStringNumberConversionStrictEqualityTruthiness.concept3"), formatMessage('zh', "ui.templateStringsStringNumberConversionStrictEqualityTruthiness.concept4"), formatMessage('zh', "ui.templateStringsStringNumberConversionStrictEqualityTruthiness.concept5"), formatMessage('zh', "ui.templateStringsStringNumberConversionStrictEqualityTruthiness.concept6")], 6),
    collections: topic(formatMessage('zh', "ui.collectionOperations"), [formatMessage('zh', "ui.arrayCreateReadUpdateDeleteAndReadOnly.concept1"), formatMessage('zh', "ui.arrayCreateReadUpdateDeleteAndReadOnly.concept2"), formatMessage('zh', "ui.arrayCreateReadUpdateDeleteAndReadOnly.concept3"), formatMessage('zh', "ui.arrayCreateReadUpdateDeleteAndReadOnly.concept4"), formatMessage('zh', "ui.arrayCreateReadUpdateDeleteAndReadOnly.concept5"), formatMessage('zh', "ui.arrayCreateReadUpdateDeleteAndReadOnly.concept6"), formatMessage('zh', "ui.arrayCreateReadUpdateDeleteAndReadOnly.concept7")], 4),
    control: topic(formatMessage('zh', "ui.branchesAndLoops"), [formatMessage('zh', "ui.ifElseAndTernaryExpressionsClassicForDifferences2.concept1"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsClassicForDifferences2.concept2"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsClassicForDifferences2.concept3"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsClassicForDifferences2.concept4"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsClassicForDifferences2.concept5"), formatMessage('zh', "ui.ifElseAndTernaryExpressionsClassicForDifferences2.concept6")], 6),
    functions: topic(formatMessage('zh', "ui.functionsAndLambdas"), [formatMessage('zh', "ui.functionTypesAndArrowFunctionsOptionalDefaultRest.concept1"), formatMessage('zh', "ui.functionTypesAndArrowFunctionsOptionalDefaultRest.concept2"), formatMessage('zh', "ui.functionTypesAndArrowFunctionsOptionalDefaultRest.concept3"), formatMessage('zh', "ui.functionTypesAndArrowFunctionsOptionalDefaultRest.concept4"), formatMessage('zh', "ui.functionTypesAndArrowFunctionsOptionalDefaultRest.concept5"), formatMessage('zh', "ui.functionTypesAndArrowFunctionsOptionalDefaultRest.concept6")], 4),
    objects: topic(formatMessage('zh', "ui.classesAndInterfaces"), [formatMessage('zh', "ui.interfaceTypeAndStructuralTypingConstructorAndParameter.concept1"), formatMessage('zh', "ui.interfaceTypeAndStructuralTypingConstructorAndParameter.concept2"), formatMessage('zh', "ui.interfaceTypeAndStructuralTypingConstructorAndParameter.concept3"), formatMessage('zh', "ui.interfaceTypeAndStructuralTypingConstructorAndParameter.concept4"), formatMessage('zh', "ui.interfaceTypeAndStructuralTypingConstructorAndParameter.concept5"), formatMessage('zh', "ui.interfaceTypeAndStructuralTypingConstructorAndParameter.concept6")], 4),
    idioms: topic(formatMessage('zh', "ui.syntaxShortcutsAndTypeNarrowing"), [formatMessage('zh', "ui.destructuringSpreadDiscriminatedUnionsAsConstAndSatisfies.concept1"), formatMessage('zh', "ui.destructuringSpreadDiscriminatedUnionsAsConstAndSatisfies.concept2"), formatMessage('zh', "ui.destructuringSpreadDiscriminatedUnionsAsConstAndSatisfies.concept3"), formatMessage('zh', "ui.destructuringSpreadDiscriminatedUnionsAsConstAndSatisfies.concept4"), formatMessage('zh', "ui.destructuringSpreadDiscriminatedUnionsAsConstAndSatisfies.concept5"), formatMessage('zh', "ui.destructuringSpreadDiscriminatedUnionsAsConstAndSatisfies.concept6")], 4),
    types: topic(formatMessage('zh', "ui.advancedTypes"), [formatMessage('zh', "ui.genericConstraintsAndKeyofIndexedAccessTypesMapped.concept1"), formatMessage('zh', "ui.genericConstraintsAndKeyofIndexedAccessTypesMapped.concept2"), formatMessage('zh', "ui.genericConstraintsAndKeyofIndexedAccessTypesMapped.concept3"), formatMessage('zh', "ui.genericConstraintsAndKeyofIndexedAccessTypesMapped.concept4"), formatMessage('zh', "ui.genericConstraintsAndKeyofIndexedAccessTypesMapped.concept5"), formatMessage('zh', "ui.genericConstraintsAndKeyofIndexedAccessTypesMapped.concept6"), formatMessage('zh', "ui.genericConstraintsAndKeyofIndexedAccessTypesMapped.concept7")], 2),
    errors: topic(formatMessage('zh', "ui.exceptionsAndModules"), [formatMessage('zh', "ui.unknownInTryCatchCustomErrorImportExport.concept1"), formatMessage('zh', "ui.unknownInTryCatchCustomErrorImportExport.concept2"), formatMessage('zh', "ui.unknownInTryCatchCustomErrorImportExport.concept3"), formatMessage('zh', "ui.unknownInTryCatchCustomErrorImportExport.concept4"), formatMessage('zh', "ui.unknownInTryCatchCustomErrorImportExport.concept5")], 4),
    async: topic(formatMessage('zh', "ui.async"), [formatMessage('zh', "ui.promiseGenericsAsyncAwaitReturnTypesConcurrentPromises.concept1"), formatMessage('zh', "ui.promiseGenericsAsyncAwaitReturnTypesConcurrentPromises.concept2"), formatMessage('zh', "ui.promiseGenericsAsyncAwaitReturnTypesConcurrentPromises.concept3"), formatMessage('zh', "ui.promiseGenericsAsyncAwaitReturnTypesConcurrentPromises.concept4"), formatMessage('zh', "ui.promiseGenericsAsyncAwaitReturnTypesConcurrentPromises.concept5"), formatMessage('zh', "ui.promiseGenericsAsyncAwaitReturnTypesConcurrentPromises.concept6")], 2),
    design: topic(formatMessage('zh', "ui.dependencyInjectionAndComposition"), [formatMessage('zh', "ui.interfaceAndConstructorInjectionFunctionTypeInjectionFake.concept1"), formatMessage('zh', "ui.interfaceAndConstructorInjectionFunctionTypeInjectionFake.concept2"), formatMessage('zh', "ui.interfaceAndConstructorInjectionFunctionTypeInjectionFake.concept3"), formatMessage('zh', "ui.interfaceAndConstructorInjectionFunctionTypeInjectionFake.concept4"), formatMessage('zh', "ui.interfaceAndConstructorInjectionFunctionTypeInjectionFake.concept5")], 2),
  },
} satisfies Record<Language, Record<string, TopicSpec>>;

export type LanguageSelection = { language: Language; topic: string };
export type DrillContent = {
  title: string; introduction: string; starterCode: string; templateCode: string; requirements: string[];
  exercises: { title: string; instruction: string; concepts: string[]; explanation: string; benefits: string[]; pitfalls: string[] }[];
};
export type LanguageDrill = DrillContent & LanguageSelection & {
  id: string; createdAt: string; updatedAt: string; code: string; concepts: string[]; revealedAt?: string; selectionTopic?: string;
};
export function languageSelection(value: unknown): LanguageSelection {
  const v = object(value);
  if (typeof v.language !== "string" || !Object.hasOwn(LANGUAGES, v.language) || typeof v.topic !== "string" ||
      (v.topic !== "auto" && !Object.hasOwn(LANGUAGE_SYLLABUS[v.language as Language], v.topic))) throw new AppError(400, formatMessage('zh', "ui.pleaseChooseAValidLanguageAndPracticeDirection"));
  return { language: v.language as Language, topic: v.topic };
}
export function languageFocus(selection: LanguageSelection, drills: LanguageDrill[]) {
  const syllabus: Record<string, TopicSpec> = LANGUAGE_SYLLABUS[selection.language];
  const count = (concept: string, id: string) => drills.filter(d => d.language === selection.language && d.topic === id && d.concepts.includes(concept)).length;
  const topics = Object.entries(syllabus);
  const id = selection.topic === "auto"
    ? topics.find(([id, spec]) => spec.concepts.some(c => !count(c, id)))?.[0]
      ?? [...topics].sort(([a, x], [b, y]) => x.concepts.reduce((n, c) => n + count(c, a), 0) / x.concepts.length - y.concepts.reduce((n, c) => n + count(c, b), 0) / y.concepts.length)[0][0]
    : selection.topic;
  const spec = syllabus[id];
  const concepts = [...spec.concepts].sort((a, b) => count(a, id) - count(b, id)).slice(0, spec.batch);
  return { language: selection.language, topic: id, spec, concepts };
}
function strings(value: unknown, min = 0, max = 12): string[] {
  if (!Array.isArray(value) || value.length < min || value.length > max) throw new AppError(400, formatMessage('zh', "ui.invalidLanguageExerciseListFormat"));
  return value.map(v => text(v, 6000));
}
export function drillContent(value: unknown, focus: string[]): DrillContent {
  const v = object(value);
  if (!Array.isArray(v.exercises) || v.exercises.length < 1 || v.exercises.length > 6) throw new AppError(400, formatMessage('zh', "ui.incorrectNumberOfLanguageExercises"));
  const exercises = v.exercises.map(value => {
    const e = object(value), concepts = strings(e.concepts, 1, 6);
    if (concepts.some(c => !focus.includes(c))) throw new AppError(400, formatMessage('zh', "ui.knowledgePointDoesNotMatchTheQuestion"));
    return { title: text(e.title, 150), instruction: text(e.instruction, 5000), concepts,
      explanation: text(e.explanation, 6000), benefits: strings(e.benefits, 1), pitfalls: strings(e.pitfalls) };
  });
  if (focus.some(c => !exercises.some(e => e.concepts.includes(c)))) throw new AppError(400, formatMessage('zh', "ui.theLanguageExercisesDoNotCoverThisKnowledge"));
  return { title: text(v.title, 150), introduction: text(v.introduction, 6000), starterCode: text(v.starterCode, 30000),
    templateCode: text(v.templateCode, 50000), requirements: strings(v.requirements, 1), exercises };
}
